### PR TITLE
Breeze dark schema

### PR DESCRIPTION
**Pull request by fabianski7**
Is just an attempt to bring some of the breeze theme colors into the QOwnNotes xD editor

**QON**

**Kate with breeze dark**

### CODE REVIEW

**Comment by pbek** [comment]
Thank you 😁 
The `FallbackSchema` setting is missing, I will add one.

**Comment by pbek** [comment]
## 20.8.3
- added the **new editor color schema** *Breeze dark*
  (for [#1847](https://github.com/pbek/QOwnNotes/pull/1847), thank you @fabianski7)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by fabianski7** [comment]
yes, it works

**Comment by pbek** [comment]
Great, thank you for testing!

**Pull request merged**
