### PR TITLE
Create Translators-proofreaders-images

### PR DESCRIPTION
**Pull request by PurplePlums**

### CODE REVIEW

**Comment by PurplePlums** [comment]
IMAGE_01
IMAGE_02
IMAGE_03
IMAGE_04
IMAGE_05
IMAGE_07
IMAGE_06

**Comment by pbek** [comment]
Since the PR didn't add anything I created the image here: https://github.com/pbek/QOwnNotes/tree/develop/docs/content/assets/img/crowdin

**Comment by pbek** [comment]
@PurplePlums, you can now use them in https://github.com/pbek/QOwnNotes/edit/develop/docs/content/contributing/translation.md like `screenshot`.

**Comment by PurplePlums** [comment]
Yesterday I updated the file adding the images from the repository you shared.

**Comment by PurplePlums** [comment]
I think it’s updated now, curious to see it.

**Comment by pbek** [comment]
Did you already create a pull request for your changes in `translation.md`?

**Comment by PurplePlums** [comment]
OK

**Comment by PurplePlums** [comment]
# Translation

How can I help to translate QOwnNotes? 
{: .subtitle }

## Join us on Crowdin to translate QOwnNotes

crowdin

**Crowdin** is a popular Localization Management Platform for mobile apps, web,
desktop software and related assets.

You can sign up at [Crowdin](https://crowdin.com/project/qownnotes/invite) and
**translate** **QOwnNotes** to your language with easy tools.

**[QOwnNotes on Crowdin](https://crowdin.com/project/qownnotes/invite)**

Just drop me a message on Crowdin or as a [GitHub issue](https://github.com/pbek/QOwnNotes/issues)
if you want to translate QOwnNotes to a new language.

If you want to add new translations to existing languages you can do so right away.

If you are a very good speaker of an already translated language that has not be proofread yet, we are grateful for your help making the QOwnNotes experience more reliable and convenient.

Click here to see if your language is among the translated ones! 

<a href="https://crowdin.com/project/qownnotes">QOwnNotes on Crowdin</a>

Once you’ve contacted the project owner [GitHub issue](https://github.com/pbek/QOwnNotes/issues) and received permission to proofread in your language, you’re ready to go!

Please consider a few things while working on the project:

(1) Maximal accuracy will create the best user experience.

(2) Use your choice of style creatively once your translation met the requirement of picking the most identical match.

(3) It makes sense for the translation to be similarly concise and following the same formalities as the original.

(4) Let’s always use the same translations on identical source expressions:

If "trashed notes" is "gelöschte Dateien" in German, you would always translate it using this expression. Exception would be when you grammatically are bound to use an alternative, but keep it simple.



In order to find all the identical expressions, search Crowdin and see all the occurences of one term

Standardize all occurrences as good as you can, so that identical terms get identical translations.

“Note” should definitely always have just one translation.

(5) For plural please add the appropriate translation each in the corresponding block.



(6) The „%1“ tags need to be written without a space, in LTR languages you can either insert the tags from the original or write them into your translation.







(7) Use "&" in front of any letter that should be used in a shortcut, can be the same as in original but does not have to.



Thank you for helping out!

**Comment by pbek** [comment]
Bitte die Bilder wie in https://github.com/pbek/QOwnNotes/pull/1840#issuecomment-668402830 erwähnt einbinden.

Du kannst die translation.md auch direkt bearbeiten (ich sehe du hast ja schon einen "fork" unter https://github.com/PurplePlums/QOwnNotes) und dann deinen Änderungsvorschlag als "pull request" in https://github.com/pbek/QOwnNotes "vorschlagen"... Ansonsten mache ich das für dich.

**Comment by pbek** [comment]
Ich schreibe das jetzt selbst um. Der ganze Text ist ein Misch-Masch aus Markdown, HTML und Pseudo-Code 😁

**Comment by pbek** [comment]
So bitte: https://docs.qownnotes.org/en/latest/contributing/translation/

**Comment by PurplePlums** [comment]
Ok sorry, im Moment habe ich das größtenteils auf dem Handy machen müssen, ich schaue mir später an, was alles schief ging... 😔

**Comment by pbek** [comment]
Silly me switched to German, sorry...

> Pseudo-Code habe ich nicht geschrieben, hatte einen Teil kopiert, das du geschrieben hast, bzw. was meinst du damit...?

- `(6)` is neither markdown nor html
- the quotes (e.g. `„`) are all incompatible to html

**Comment by PurplePlums** [comment]
I already answered that I filled in the whole guidelines after the text you’ve written but for whatever reason you didn’t got to read it. Hence when you’ve asked a second time I copied from my iPhone notes, so very sorry.

I want to see how this works and add my line for possible proofreader coaching, I think I got the message.

**Pull request closed without merging**
