### PR TITLE
notehistory: Use note id directly instead of querying database

### PR DESCRIPTION
**Pull request by Waqar144**
Performance improvements

### CODE REVIEW

**Comment by pbek** [comment]
Does the note history still work if you restart the application (are the correct notes of the last session found in the history at the correct position)?

**Comment by pbek** [comment]
Because it seems you are now relying on note ids (which are not persisted on disk!) instead of the note name and sub-folder!

**Comment by Waqar144** [comment]
Yes, that's not happening. I was going to use the existing implementation as fallback, so that the note history is correctly loaded, and with time after the first time, note id would be used. But I wanted you to take a look at this before I went any further (as this may have other side effects that I may not be aware of)

**Comment by pbek** [comment]
> and with time after the first time, note id would be used.

and if the note folder is reloaded (and the note index is regenerated)?

**Comment by Waqar144** [comment]
> and if the note folder is reloaded (and the note index is regenerated)?

If the index is regenerated then yeah, the old note_ids would be pretty much useless for this purpose.

**Comment by pbek** [comment]
> If the index is regenerated then yeah, the old note_ids would be pretty much useless for this purpose.

do you have to adapt your implementation?

**Comment by Waqar144** [comment]
> do you have to adapt your implementation?

```cpp
             if (item.getNoteId() == note.getId()) {
                 return item;
            } else if (item.getNote().getId() == note.getId()){
               return item;
             }
```

This would work, but its pointless, since we are doing the same thing as before.

We can have something like:
```cpp
     //first for loop
        for (int i = 0; i < noteHistory->count(); ++i) {
         ....
        }
//fall back.
        for (int i = 0; i < noteHistory->count(); ++i) {
            const NoteHistoryItem &item = noteHistory->at(i);

            if (item.getNote().getId() == note.getId()){
                return item;
            }
        }
```

**Comment by Waqar144** [comment]
Are you getting a lag while switching notes (happens sometimes, often with small notes)?

**Comment by pbek** [comment]
> Are you getting a lag while switching notes (happens sometimes, often with small notes)?

you mean with this PR or in general? in general I can't say that I see any lags.

**Comment by pbek** [comment]
> This would work, but its pointless, since we are doing the same thing as before.

You could just also wipe the NoteIds in the history when all notes are wiped off the database... But the problem is notes can also be removed individually, you would also need to handle that...

Is this all really worth the effort? Is there such a high note switching speed improvement?

**Comment by Waqar144** [comment]
> You could just also wipe the NoteIds in the history when all notes are wiped off the database... But the problem is notes can also be removed individually (e.g. deleted or moved), you would also need to handle that...
> 
> Is this all really worth the effort? Is there such a high note switching speed improvement?

Not really, It just gives me a 12ms lag at most.
This was a small lag I noticed.

Going after this is going to cause more regressions and a lot of effort. I will close this now.

**Comment by Waqar144** [comment]
> you mean with this PR or in general? in general I can't say that I see any lags.

It is happening with 2 or 3 specific notes. I have tried really hard to find out where the lag is happening but have been unable to do so till now. Maybe it is something related to the note file.

**Comment by pbek** [comment]
12ms for a in-memory sqlite query by string? Seems high. How many notes do you have? Maybe we should use more sqlite indices.

**Comment by Waqar144** [comment]
> 12ms for a in-memory sqlite query by string? Seems high. How many notes do you have? Maybe we should use more sqlite indices.

about 34 or so where I am testing. 

Each call to `getNote()` is taking about a 300 - 600 microseconds usually on my pc.

**Comment by pbek** [comment]
You could try to add an index for the note table.

**Pull request closed without merging**
