### PR TITLE
Fix expression in brackets being converted to link in preview

### PR DESCRIPTION
**Pull request by Waqar144**
#1794

### CODE REVIEW

**Comment by pbek** [comment]
Tests are failing on Windows. 😁

**Comment by pbek** [comment]
Inline code blocks still have the same issue with `def foo[A](a: A)`. :grimacing:

**Comment by Waqar144** [comment]
> Inline code blocks still have the same issue with `def foo[A](a: A)`. grimacing

Really? I just checked and the issue is fixed on my side :thinking: Did you try it with some other code sample or the same one?

**Comment by pbek** [comment]
image

**Comment by Waqar144** [comment]
hmm those are different things.

The second one is not so easy I am afraid haha. The conversion is being handled by `MD4C` for that.

**Pull request merged**
