### PR TITLE
Call updateCurrentNote() only once when setting the note

### PR DESCRIPTION
**Pull request by Waqar144**
Huge performance improvement especially for big notes.
#1359

### CODE REVIEW

**Comment by pbek** [comment]
Great! :tada:

**Comment by Waqar144** [comment]
Also,
I think if we override the setText method in QOwnNotesMarkDownTextEdit, we can check for stuff like CodeBlocks, Comments, Front Matter and Broken Links.. before setting the text. We can then turn off these highlighting options based on the results. After setting the text, we can turn everything on again so that new text gets highlighted properly.

**Comment by pbek** [comment]
Sounds like a good idea, but what happens if a text block changes later (aka. "the user edits the note")?

**Comment by pbek** [comment]
Sounds good. :smile_cat:

**Comment by Waqar144** [comment]
> Sounds good. smile_cat

I will try it, if it works good, I will send in the code for testing

**Pull request merged**
