### PR TITLE
Implement filtering by multiple tags

### PR DESCRIPTION
**Pull request by Waqar144**
#327

### CODE REVIEW

**Comment by pbek** [comment]
I knew you will take tags up too! :grin: 
Doesn't seem to work in every situation for me when unselecting tags.

https://imgur.com/a/6fKXtNO

**Comment by pbek** [comment]
After single selecting I selected two tags, that worked. But when un-selecting tags notes wasn't filtered correctly. I guess that's because only one tag was selected any more and I clicked on the tag that I wanted un-selected. I don't know how to get around this. :grimacing:

**Comment by Waqar144** [comment]
> I knew you will take tags up too! grin
> Doesn't seem to work in every situation for me when unselecting tags.
> 
> https://imgur.com/a/6fKXtNO

It seemed pretty straightforward after I looked into it :laughing:

**Comment by Waqar144** [comment]
> After single selecting I selected two tags, that worked. But when un-selecting tags notes wasn't filtered correctly. I guess that's because only one tag was selected any more and I clicked on the tag that I wanted un-selected. I don't know how to get around this. grimacing

Fixed, I think

**Comment by pbek** [comment]
Awesome!

**Pull request merged**
