### PR TITLE
Fix multiline markup in .travis.yml

### PR DESCRIPTION
**Pull request by dandelionred**

### CODE REVIEW

**Comment by pbek** [comment]
did you close it on purpose?

**Comment by dandelionred** [comment]
Yeah. There is some parsing error when running travis.

**Comment by dandelionred** [comment]
```

$ if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
  if [ "${TRAVIS_BRANCH}" != "master" ]; then
       ./../bin/tests/tests -platform minimal -txt
    && ../travis/linux/coveralls.sh
    ;
  fi
  ;
else
     ./../bin/tests/tests.app/Contents/MacOS/tests -platform minimal -txt
  ;
fi
/home/travis/.travis/functions: eval: line 107: syntax error near unexpected token `&&'
/home/travis/.travis/functions: eval: line 107: `    && ../travis/linux/coveralls.sh'
The command "if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
  if [ "${TRAVIS_BRANCH}" != "master" ]; then
       ./../bin/tests/tests -platform minimal -txt
    && ../travis/linux/coveralls.sh
    ;
  fi
  ;
else
     ./../bin/tests/tests.app/Contents/MacOS/tests -platform minimal -txt
  ;
fi
" exited with 1.

```

**Comment by dandelionred** [comment]
And the same was in another pull request when I moved `&&` to the line above
```
$ if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
  if [ "${TRAVIS_BRANCH}" != "master" ]; then
       ./../bin/tests/tests -platform minimal -txt && ../travis/linux/coveralls.sh
    ;
  fi
  ;
else
     ./../bin/tests/tests.app/Contents/MacOS/tests -platform minimal -txt
  ;
fi
/home/travis/.travis/functions: eval: line 107: syntax error near unexpected token `;'
/home/travis/.travis/functions: eval: line 107: `    ;'
The command "if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
  if [ "${TRAVIS_BRANCH}" != "master" ]; then
       ./../bin/tests/tests -platform minimal -txt && ../travis/linux/coveralls.sh
    ;
  fi
  ;
else
     ./../bin/tests/tests.app/Contents/MacOS/tests -platform minimal -txt
  ;
fi
" exited with 1.
```

**Pull request closed without merging**
