### PR TITLE
Use fwd declarations for faster compile times

### PR DESCRIPTION
**Pull request by Waqar144**

### CODE REVIEW

**Comment by pbek** [comment]
Windows build is failing:

```
LIB -DQT_CORE_LIB -DQT_NEEDS_QMAIN -I. -Ilibraries -Ilibraries/qmarkdowntextedit -Ilibraries/qmarkdowntextedit -Ilibraries/qmarkdowntextedit -Ilibraries/piwiktracker -Ilibraries -Ilibraries/qkeysequencewidget/qkeysequencewidget/src -Ilibraries/qttoolbareditor/src -Ilibraries/fakevim/fakevim/utils -Ilibraries/fakevim/fakevim -Ilibraries/singleapplication -Ilibraries/sonnet/src/core -Ilibraries/sonnet/src/plugins/hunspell/hunspell/src/hunspell -Ilibraries/sonnet/src/plugins/hunspell/hunspell/src/parsers -I../../core -Ihunspell/src/hunspell -Ihunspell/src/ -I../../../Qt/5.13/mingw73_32/include -I../../../Qt/5.13/mingw73_32/include/QtSvg -I../../../Qt/5.13/mingw73_32/include/QtPrintSupport -I../../../Qt/5.13/mingw73_32/include/QtWidgets -I../../../Qt/5.13/mingw73_32/include/QtGui -I../../../Qt/5.13/mingw73_32/include/QtANGLE -I../../../Qt/5.13/mingw73_32/include/QtSql -I../../../Qt/5.13/mingw73_32/include/QtXmlPatterns -I../../../Qt/5.13/mingw73_32/include/QtQml -I../../../Qt/5.13/mingw73_32/include/QtWebSockets -I../../../Qt/5.13/mingw73_32/include/QtNetwork -I../../../Qt/5.13/mingw73_32/include/QtXml -I../../../Qt/5.13/mingw73_32/include/QtConcurrent -I../../../Qt/5.13/mingw73_32/include/QtCore -Irelease -I. -I../../../Qt/5.13/mingw73_32/mkspecs/win32-g++  -o release/welcomedialog.o dialogs/welcomedialog.cpp
dialogs/welcomedialog.cpp: In member function 'void WelcomeDialog::on_noteFolderButton_clicked()':
dialogs/welcomedialog.cpp:212:13: error: 'QMessageBox' has not been declared
             QMessageBox::information(
             ^~~~~~~~~~~
mingw32-make[1]: *** [Makefile.Release:19907: release/welcomedialog.o] Error 1
mingw32-make[1]: Leaving directory 'C:/projects/qownnotes/src'
mingw32-make: *** [Makefile:38: release] Error 2
```

**Comment by pbek** [comment]
> Use fwd declarations

Is this a best practice to do everything via forward declaration?

**Comment by Waqar144** [comment]
> > Use fwd declarations
> 
> Is it a best practice to do everything via forward declaration?

A lot of projects do it. It wouldn't matter for overall compile time, but it does make a huge difference when you are making changes and suddenly it triggers recompilation of a lot of files.

Plus, it will reduce a lot of bloat that was getting included previously. So i think its good in a way.

**Comment by pbek** [comment]
QON doesn't build with cmake any more. :grimacing: 

```
In file included from /home/omega/Code/QOwnNotes/cmake-build-debug/src/QOwnNotes_autogen/include/ui_issueassistantdialog.h:29:0,
                 from /home/omega/Code/QOwnNotes/src/dialogs/issueassistantdialog.cpp:9:
/home/omega/Code/QOwnNotes/src/widgets/qownnotesmarkdowntextedit.h:58:46: error: ‘MarkdownHighlighter::HighlighterState’ has not been declared
     void setFormatStyle(MarkdownHighlighter::HighlighterState index);
                                              ^~~~~~~~~~~~~~~~
src/CMakeFiles/QOwnNotes.dir/build.make:630: recipe for target 'src/CMakeFiles/QOwnNotes.dir/dialogs/issueassistantdialog.cpp.o' failed
make[3]: *** [src/CMakeFiles/QOwnNotes.dir/dialogs/issueassistantdialog.cpp.o] Error 1
CMakeFiles/Makefile2:95: recipe for target 'src/CMakeFiles/QOwnNotes.dir/all' failed
make[2]: *** [src/CMakeFiles/QOwnNotes.dir/all] Error 2
CMakeFiles/Makefile2:102: recipe for target 'src/CMakeFiles/QOwnNotes.dir/rule' failed
make[1]: *** [src/CMakeFiles/QOwnNotes.dir/rule] Error 2
Makefile:164: recipe for target 'QOwnNotes' failed
make: *** [QOwnNotes] Error 2
```

**Comment by pbek** [comment]
It neither builds with qmake, and the reason lies in https://github.com/pbek/qmarkdowntextedit/pull/81

**Comment by pbek** [comment]
But I cannot get https://github.com/pbek/qmarkdowntextedit/pull/81 to run without this RP neither.

```
qownspellchecker.o: In function `QOwnSpellChecker::QOwnSpellChecker(QObject*)':
/home/omega/Code/QOwnNotes/build-QOwnNotes-Desktop-Debug/../src/helpers/qownspellchecker.cpp:22: undefined reference to `vtable for QOwnSpellChecker'
qownspellchecker.o: In function `QOwnSpellChecker::~QOwnSpellChecker()':
/home/omega/Code/QOwnNotes/build-QOwnNotes-Desktop-Debug/../src/helpers/qownspellchecker.cpp:40: undefined reference to `vtable for QOwnSpellChecker'
collect2: error: ld returned 1 exit status
Makefile:864: recipe for target 'QOwnNotes' failed
make: *** [QOwnNotes] Error 1
14:52:17: The process "/usr/bin/make" exited with code 2.
Error while building/deploying project QOwnNotes (kit: Desktop)
When executing step "Make"
```

**Comment by Waqar144** [comment]
Let me fix it

**Comment by pbek** [comment]
It already has begun. https://build.opensuse.org/package/live_build_log/home:pbek:QOwnNotes/desktop/openSUSE_13.2/i586 failed.

**Comment by pbek** [comment]
and https://build.opensuse.org/package/live_build_log/home:pbek:QOwnNotes/desktop/openSUSE_13.2/x86_64

**Comment by pbek** [comment]
Debian 8 is of course also broken. :grin:

**Comment by Waqar144** [comment]
Will fix it.

I still vote for Debian 8 to be dropped 😛

**Comment by pbek** [comment]
For some reason the operating system stats on our Matomo page doesn't work any more. :grimacing:

**Comment by Waqar144** [comment]
Since this commit or forever?

**Comment by pbek** [comment]
I don't know what the problem is. There are no stats for custom properties... But for a short while today there were stats available, seems like a Matomo problem.

**Comment by pbek** [comment]
Doesn't matter a lot, all failed builds share the same problem :grin:

**Pull request merged**
