### PR TITLE
Update get-involved.md

### PR DESCRIPTION
**Pull request by Fabijenna**
rewrote line - 18 to a shorter sentence
added - 19 for everyone to participate in a survey I wrote (might be expanded in future)

### CODE REVIEW

**Comment by Fabijenna** [comment]
> added - 19 for everyone to participate in a survey I wrote (might be expanded in future)

You want me to work more on the Survey, and is that's why you didn't include point 19?

**Comment by Fabijenna** [comment]
If yes, please list the things you'd rather have me updated. Thanks.

**Comment by pbek** [comment]
> Fill out this very short new [**survey**](https://freeonlinesurveys.com/s/nA8t17k8)!

The text was added the way you put it in and I can see it on the bottom of https://www.qownnotes.org/contributing/get-involved.html.

**Comment by pbek** [comment]
But now that I look at it I'll remove the word "new", because the survey will not be new in one month or one year when nobody is removing the word by then. 😁

**Comment by Fabijenna** [comment]
Sure. I wouldn’t have put it this way an other time.

**Pull request merged**
