### PR TITLE
Mac spellchecker performance improvement attempt

### PR DESCRIPTION
**Pull request by Waqar144**
This is an attempt to improve the performance of spellchecking on Mac. The code is changed after doing a lot of research and reading a lot of code from other projects. If we can't get any performance improvements out of this, we will just revert it.

**Warning: The code has not been compiled / tested yet as I don't have a Mac available. Best to let the Travis Mac build complete.**

#1359

### CODE REVIEW

**Comment by pbek** [comment]
Travis liked it

**Comment by Waqar144** [comment]
> Travis liked it

I am hoping it will improve performance.
Will you be able to test it any time soon?

**Comment by pbek** [comment]
Later today.
Everyone else also can, DMGs are created for each commit on https://github.com/pbek/QOwnNotes/releases

**Comment by Waqar144** [comment]
> Later today.
> Everyone else also can, DMGs are created for each commit on https://github.com/pbek/QOwnNotes/releases

Great! 
Great!

**Comment by Waqar144** [comment]
Got someone to test, for now results look the same as before. 50 secs for 160k with auto detect.

**Pull request merged**
