### PR TITLE
Update translation.md

### PR DESCRIPTION
**Pull request by Fabijenna**
Updated according to agreed content.

### CODE REVIEW

**Comment by pbek** [comment]
What's wrong with this PR? Don't you want to add this one over #2307?

**Comment by Fabijenna** [comment]
I couldn't see what you did and I thought I needed to update "having" myself so I wrote a whole other PR with also the previous updates.

I couldn't see what else I could do.

**Comment by Fabijenna** [comment]
The only new is the sentence with the "having" error, I updated.

**Comment by pbek** [comment]
Then I'll merge #2307, so you can edit it...

**Pull request closed without merging**
