### PR TITLE
Support playing gif in the preview #1104

### PR DESCRIPTION
**Pull request by liulex**
Used a tricky way to update the document resource...

### CODE REVIEW

**Comment by pbek** [comment]
Looking nice, I'll test it later.

**Comment by pbek** [comment]
It does no animation for me at

**Platform**: `linux`
**Operating System**: `KDE neon User Edition 5.14`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Self-build`
**Qt Version (build)**: `5.11.2`
**Qt Version (runtime)**: `5.11.2`

I'll investigate.

**Comment by pbek** [comment]
I had to adapt the regular expression to detect git-urls a bit: `]+src=\"(file:\/\/\/[^\"]+\.gif)\"`
Now for it animates the gif on certain interactions with the panel, like scrolling. :smile: Does it animate all the time for you? I tried a random pic from the internet:

**Comment by liulex** [comment]
Yes, it works fine on Windows. `repaint()` may have have some [problems](https://bugreports.qt.io/browse/QTBUG-4453) on Linux/macOS. I'll test it later on macOS.

**Pull request merged**
