### PR TITLE
Update mainwindow to use const for all Tag objects

### PR DESCRIPTION
**Pull request by Waqar144**

### CODE REVIEW

**Comment by pbek** [comment]
Also conflicts

**Comment by Waqar144** [comment]
resolved

**Comment by pbek** [comment]
again :)

**Comment by Waqar144** [comment]
again resolved :grin:

**Comment by pbek** [comment]
And conflicts again. lol

**Comment by pbek** [comment]
...I guess from my fix for #1413

**Comment by Waqar144** [comment]
> ...I guess from my fix for #1413

Haha yes.
Ok so , once more resolved :grinning:

**Comment by pbek** [comment]
finally :D

**Pull request merged**
