### PR TITLE
Fix etc being marked misspelled for en_GB

### PR DESCRIPTION
**Pull request by Waqar144**
#1399

### CODE REVIEW

**Comment by pbek** [comment]
I don't like that fix at all... Hardcoded string comparisons that will hit every word for every language... :crying_cat_face:

**Comment by Waqar144** [comment]
> I don't like that "fix" at all... Hardcoded string comparisons that will hit every word for every language... crying_cat_face

There are two other solutions:
- User adds it to their personal dictionary. It will get ignored
- User repairs the en_GB dic to not mark etc. as misspelled
- en_GB fixes itself

On our side that's all we can do.

**Comment by pbek** [comment]
Other languages and other abbreviations are affected too, see https://github.com/pbek/QOwnNotes/issues/1399#issuecomment-552582204

**Comment by Waqar144** [comment]
> Other languages and other abbreviations are affected too, see [#1399 (comment)](https://github.com/pbek/QOwnNotes/issues/1399#issuecomment-552582204)

I did.
Closing the PR. Fixable on the user side.

**Comment by pbek** [comment]
We cannot "fix" every abbreviation anyway...

**Comment by Waqar144** [comment]
> We cannot "fix" every abbreviation anyway...

Yes, and there's going to be a lot of users with such problems. We can't handle dictionary problems. Unless we were hosting the dictionaries ourselves

**Comment by Waqar144** [comment]
How about we host dictionaries here in a repo?

**Comment by pbek** [comment]
https://github.com/qownnotes/dictionaries

**Pull request closed without merging**
