### PR TITLE
Remove levenshtein similarity check

### PR DESCRIPTION
**Pull request by Waqar144**
It's slowing everything down too much.

https://github.com/pbek/QOwnNotes/issues/2433

### CODE REVIEW

**Comment by pbek** [comment]
I don't really want to remove this until there is another solution. It works great for almost all notes to get around those "somethings gets updated by an external process while or after you were editing a note" issues.

**Comment by Waqar144** [comment]
> I don't really want to remove this until there is another solution. It works great for almost all notes to get around those "somethings gets updated by an external process while or after you were editing a note" issues.

For tiny notes, yes.

**Comment by pbek** [comment]
> For tiny notes, yes.

I wouldn't call a few 100kB tiny... If you want we can add a simple size check to decide if we want the similarity check...

**Comment by Waqar144** [comment]
On linux, I haven't encountered any file watcher issues (probably because I don't sync and change things not very often). But on other systems its a common issue. And so I can't imagine the pain everyone would be going through everytime this code path is triggered (which is a lot given the number of externally modified issues here). This is completely broken for anything larger than a couple of kilobytes

**Comment by pbek** [comment]
I wouldn't call 93.8 KB tiny neither for plain text files. All my notes are below 93.8 KB! Even the QOwnNotes Todo list...

**Comment by Waqar144** [comment]
93K is tiny. You may have different standards, but for a computer that can process billions of instructions per second and has a throughput of multi GB/s, this is nothing.

**Comment by pbek** [comment]
You are right, I re-evaluated. It takes too long even in single digit kB notes.

**Comment by Waqar144** [comment]
I think `QSignalBlock`ing the watcher doesn't work well. On the other hand, if we disconnect -> reconnect, that is a lot more reliable as there will be no signals coming through.

For cases where there really was an external modification by an external program triggered by the user, the dialog is necessary.

**Pull request closed without merging**
