### PR TITLE
Add css and yaml highlighter

### PR DESCRIPTION
**Pull request by Waqar144**
- Minor fix for numeric highlighting
- Full css highlighting
- Partial YAML highlighting (very painful)

### CODE REVIEW

**Comment by pbek** [comment]
Awesome!

**Comment by pbek** [comment]
Your test fails: `FAIL!  : TestNotes::testCodeToHtmlNumericLiterals() 'badr == eBad' returned FALSE. ()
   Loc: [testcases/app/test_notes.cpp(217)]`

**Comment by pbek** [comment]
Is this serious? I just wanted to make a release...

**Comment by Waqar144** [comment]
> Your test fails: `FAIL! : TestNotes::testCodeToHtmlNumericLiterals() 'badr == eBad' returned FALSE. () Loc: [testcases/app/test_notes.cpp(217)]`

Definitely serious.

Numeric highlighting doesn't work properly if you have something like this: a123

I guess it broke from all the recent changes. Good thing I wrote the tests

**Pull request merged**
