### PR TITLE
Disable spellchecking in logTextEdit

### PR DESCRIPTION
**Pull request by Waqar144**
#1423

### CODE REVIEW

**Comment by pbek** [comment]
I wonder if wouldn't be better to set a flag or something to disable the spellchecker and not checking the the object name. 😁 
I guess we should also disable spellchecking in the *Debug settings*.

**Comment by Waqar144** [comment]
> I wonder if wouldn't be better to set a flag or something to disable the spellchecker and not checking the the object name....

There seems to be no simple way to do that. 
I will find a way around it.

**Comment by pbek** [comment]
> There seems to be no simple way to do that.

I thought as much. :grin: 

>  I will find a way around it.

:tada:

**Comment by pbek** [comment]
If it's too bad let's stay at checking the object names... (and add a check for the debug information text edit, maybe via a QStringList with all the object names)

**Comment by Waqar144** [comment]
> If it's too bad let's stay at checking the object names... (and add a check for the debug information text edit, maybe via a QStringList with all the object names)

For now,
`Spellchecker` doesn't get initialized except when we set the note text using `setText()`. Note text is set only for `noteTextEdit` so spell checking stays disabled for everything else. What do you think?

**Comment by pbek** [comment]
Sounds great. Thank you!

**Comment by pbek** [comment]
Ah, you also need to add `encryptedNoteTextEdit`. :laughing:

**Comment by Waqar144** [comment]
> Ah, you also need to add `encryptedNoteTextEdit`. laughing

It works for that too. I mean spellchecking is enabled inside it. :wink: Though there's not any point in spellchecking the encrypted text :laughing:

**Comment by pbek** [comment]
> It works for that too. I mean spellchecking is enabled inside it. 

are you sure?

> Though there's not any point in spellchecking the encrypted text laughing

no, it's the other way around. `encryptedNoteTextEdit` is used to actually edit the encrypted notes. The encrypted note text is then written to `noteTextEdit` to be stored in the note file.

**Comment by Waqar144** [comment]
> > It works for that too. I mean spellchecking is enabled inside it.
> 
> are you sure?

Yeah it's working,
I just encrypted a note and then decrypted it. Spell checking is working. 

However, 
Post issue, feature request, menu action is not working. Crashes the app

**Comment by Waqar144** [comment]
> Issue Assistant is not working. Crashes the app

Fixed

**Pull request merged**
