### PR TITLE
Fix unable to switch to root folder directly

### PR DESCRIPTION
**Pull request by Waqar144**

### CODE REVIEW

**Comment by pbek** [comment]
Every time I click on a note sub-folder it gets loaded twice now.

**Comment by pbek** [comment]
I fixed that now. I just needed to remove this PR and remove `NoteSubFolder::setAsActive(subFolderId);` from your last PR. Why did you need `NoteSubFolder::setAsActive(subFolderId);`?

**Comment by Waqar144** [comment]
> I fixed that now. I just needed to remove this PR and remove `NoteSubFolder::setAsActive(subFolderId);` from your last PR.

ok

Why did you need `NoteSubFolder::setAsActive(subFolderId);`?

I thought setting as 'active' and then jumping to that folder was the way. I just didn't test without it :(

**Comment by pbek** [comment]
`jumpToNoteSubFolder` should do fine on it's own, it's also used in the scriptping engine ;)

**Comment by pbek** [comment]
> I thought setting as 'active' and then jumping to that folder was the way. I just didn't test without it :(

note sub-folder are pretty complex already, because all the things you can do in the *Panel settings* (e.g. like also show all notes of the sub-folders recursively)

**Comment by Waqar144** [comment]
> `jumpToNoteSubFolder` should do fine on it's own, it's also used in the scriptping engine ;)

Yes,

I just tried this. It works, but the root folder switching isn't working

**Comment by pbek** [comment]
> I just tried this. It works, but the root folder switching isn't working

Oh, then it's not fixed yet, because I can't reproduce it. :( I just added your `setAsActive` again and I'm still able to jump to the root folder, what settings did you use to reproduce it?

**Comment by Waqar144** [comment]
> > I just tried this. It works, but the root folder switching isn't working
> 
> Oh, then it's not fixed yet, because I can't reproduce it. :( I just added your `setAsActive` again and I'm still able to jump to the root folder, what settings did you use to reproduce it?

It works all the time. Except when you have these 'panel settings' checked:
- Show all notes in a folder including their subfolders
- Display note subfolders as full tree

**Comment by pbek** [comment]
Strange. I have (and had) those two activated.

**Comment by Waqar144** [comment]
This is how my subFolderTreeWidget looks like to reproduce this issue:

image

**Comment by Waqar144** [comment]
And my panel settings:

image

**Comment by pbek** [comment]
Settings are the same, folders almost (I have a deeper tree). And you can't click on "Notes" after you jumped to a sub-folder?

**Comment by Waqar144** [comment]
> Settings are the same, folders almost (I have a deeper tree). And you can't click on "Notes" after you jumped to a sub-folder?

Yeah exactly. Clicking on it doesn't reload the `noteTreeWidget`

**Comment by pbek** [comment]
> Clicking on it doesn't reload the noteTreeWidget

But you can click on "Notes" and it is then selected?

**Comment by pbek** [comment]
For me the noteTreeWidget gets the correct notes.

**Comment by Waqar144** [comment]
> > Clicking on it doesn't reload the noteTreeWidget
> 
> But you can click on "Notes" and it is then selected?

Yeah it does get selected. And after you click 5 or 6 times, the notes get loaded

**Comment by Waqar144** [comment]
Here's a small gif

Peek 2019-11-26 12-48

**Comment by pbek** [comment]
> Yeah it does get selected. And after you click 5 or 6 times, the notes get loaded

I see, you need to previously be on the "Notes" folder, not on any other folder. I can reproduce it now.

**Comment by Waqar144** [comment]
> I see, you need to previously be on the "Notes" folder, not on any other folder. I can reproduce it now.

Great. Welcome to the party :laughing:

**Comment by pbek** [comment]
Tricky, this needs to be fixed in `MainWindow::jumpToNoteSubFolder`.

**Comment by pbek** [comment]
That did the trick for me:

```cpp
bool MainWindow::jumpToNoteSubFolder(int noteSubFolderId) {
    QTreeWidgetItem* item =
            Utils::Gui::getTreeWidgetItemWithUserData(
                ui->noteSubFolderTreeWidget, noteSubFolderId);

    if (item != Q_NULLPTR) {
        ui->noteSubFolderTreeWidget->setCurrentItem(item);

        return true;
    }

    return false;
}
```

**Comment by Waqar144** [comment]
> That did the trick for me:
> 
> ```c++
> bool MainWindow::jumpToNoteSubFolder(int noteSubFolderId) {
>     QTreeWidgetItem* item =
>             Utils::Gui::getTreeWidgetItemWithUserData(
>                 ui->noteSubFolderTreeWidget, noteSubFolderId);
> 
>     if (item != Q_NULLPTR) {
>         ui->noteSubFolderTreeWidget->setCurrentItem(item);
> 
>         return true;
>     }
> 
>     return false;
> }
> ```

That makes the function a lot cleaner.

We can also just directly set the Item in the customContextMenu function. But that would lead to duplicate code.

**Comment by pbek** [comment]
> We can also just directly set the Item in the customContextMenu function.

we don't have the item there, don't we?

**Comment by Waqar144** [comment]
> > We can also just directly set the Item in the customContextMenu function.
> 
> we don't have the item there, don't we?

We can create it though

**Comment by pbek** [comment]
why? `MainWindow::jumpToNoteSubFolder` already does that and is also used elsewhere

**Comment by Waqar144** [comment]
> why? `MainWindow::jumpToNoteSubFolder` already does that and is also used elsewhere

I also mean it's better to use the function.

**Pull request merged**
