### PR TITLE
Remove current line highlight code from QOwnNotesMarkdownTextEdit

### PR DESCRIPTION
**Pull request by Waqar144**
The feature is now implemented in QMarkdownTextEdit. We just need to
enable it according to our settings.

### CODE REVIEW

**Comment by pbek** [comment]
When you turn on/off the highlighting of the current line in the settings the highlighting is still the way it was until you restart the app.

**Comment by Waqar144** [comment]
Hmm, I guess we don't update settings if settings are changed. Do you want the fix in this PR? Otherwise I will do a follow up tomorrow

**Comment by pbek** [comment]
Can you do it please, I didn't have the time.

**Comment by Waqar144** [comment]
its done.

**Comment by pbek** [comment]
>  @Waqar144 Waqar144 force-pushed the work/curln-hi branch from e471945 to 0663377 6 hours ago 

please no force pushes, I can't review them 😅

**Comment by pbek** [comment]
> its done.

thank you!

**Pull request merged**
