### PR TITLE
[website] improve the navbar and sidebar

### PR DESCRIPTION
**Pull request by noureddin**
As discussed in #2494, then in the Telegram/Matrix room ([start [on Matrix]](https://matrix.to/#/!rUzrRvrnrOsLasDdbp:matrix.org/$oqpz48AHfk1tvdjbCw-L1sK3ax4xmcVkHvV-ewtmWlA?via=matrix.org&via=gitter.im&via=ewonchang.com), [end [on Matrix]](https://matrix.to/#/!rUzrRvrnrOsLasDdbp:matrix.org/$RTHMUsM0bUBsEY7kzm2iMiC0UVK0b1gzjz9zmEPJJfk?via=matrix.org&via=gitter.im&via=ewonchang.com)) with the Head of Translation,

This PR add links to the English Blog in the navbar and sidebar in all languages on the website.

The navbar link is a link to the English `/blog/`.

I couldn't make the blog in the sidebar just a link, so I made it identical to the English one: containing "Overview" (in English) and titles of the Blog posts (in English), and clicking on any of them opens it in English.

I did my best to provide the best and most consistent translations for "Blog (in English)" in all languages. A native or fluent speaker is still needed though.

### CODE REVIEW

**Comment by noureddin** [comment]
By the way, I'm open to removing the blog from the sidebar in other languages, relying only on the link in the navbar.

**Comment by noureddin** [comment]
> Sounds like a good idea, but the text in the menu is so long now that screens with certain resolutions don't show the full menu any more (try resizing your browser window)... It would need changes in the CSS for responsiveness...

The navbar? I guess so. I'll look if I can do something.

**Comment by noureddin** [comment]
Under certain resolution, the navbar is converted to a burger menu. The problem is that just above this resolution, even in English, some items are hidden.

A second problem I just noticed: that burger menu is completely messing up the website in RTL languages. 😅

I don't know even how to start on the first problem. But I will give the second one a try.

**Comment by noureddin** [comment]
For the second problem (the burger menu in RTL), this diff (to `index.styl` only) solves it:

<details><summary><code>fix burger menu in RTL narrow windows</code></summary>

```diff
diff --git a/webpage/src/.vuepress/styles/index.styl b/webpage/src/.vuepress/styles/index.styl
index e617bf0..4fb1023 100755
--- a/webpage/src/.vuepress/styles/index.styl
+++ b/webpage/src/.vuepress/styles/index.styl
@@ -83,8 +83,15 @@ html[dir="rtl"]
   .sidebar-heading
     padding-left 0
     padding-right 1.5rem
+
+  .sidebar
+    padding-left 1.5rem
+    padding-right 0
+
+  .sidebar-heading, .sidebar
     .arrow
       right: 0.35em
+      margin-right: 0.35em
     .arrow.right
       transform: rotate(180deg)
 
@@ -120,10 +127,15 @@ html[dir="rtl"]
 
   .sidebar
     left auto !important
-    right 0
+    right 0 !important
     border-right medium none color
     border-left 1px solid $borderColor
     direction rtl
+    transform none
+    transition right 0.5s linear
+
+  .theme-container.no-sidebar:not(.sidebar-open) .sidebar
+    right -100vw !important
 
   a.header-anchor
     float right !important
```

</details>

I just learned the hard way why I should never push to the primary branch, even when I'm the owner of (a fork of) a repo.

Can I make that change in a commit to this same PR? 😅

If you don't like to accept this PR, allow me to know so I remove it and make a different PR with that fix.

---

For the first problem, which affects all languages including English (which is not touched in anyway in this PR), the culprit is this (beautified) CSS code somewhere in the processed CSS (`webpage/src/.vuepress/dist/assets/css/0.styles.xxxxxxxx.css`):

```css
@media (max-width:719px) {
    /* ... */
    .navbar .can-hide {
        display: none
    }
}
```

This number should be increased in order to show the burger menu when the window is still a bit wide but some links are not shown.

This number is defined in the variable `$MQMobile` in `node_modules/@vuepress/core/lib/client/style/config.styl`.

The problem is that this number is used in many media queries all over the CSS, and changing it only for `.navbar .can-hide` won't work (for example, the links themselves won't show), and I don't know how to change something in a VuePress theme without changing files inside `node_modules`.

So… May I suggest reducing the number of links instead? I have three suggestions:

1. We may change "Languages" to a globe emoji, or an SVG icon, or a flag emoji representing each language.

2. The Blog is already in the sidebar, so I think it's safe to be removed from the navbar. I would also suggest adding a button for it in the home page, under the features but above the RSS buttons.

3. I don't think that the changelog needs to be in the navbar, visible all the time. So I would suggest moving it to the sidebar, too.

As a test, after applying this PR, I removed the changelog link and changed the "Languages" label to "🌐", and, at a width of 754px, all the languages had all the links shown (some except GitHub). Only French had no globe (the languages link), and Dutch and Hungarian had a partial globe. I think for these three languages we may have only "Blog" without the "(in English)" part, or maybe remove the Blog link entirely for all languages, but keep it in the sidebar.

Again, all of that is a completely different issue from the one targeted in this PR. I suggest I open a different issue to discuss it there (primarily focusing on English, with other languages in mind).

**Comment by pbek** [comment]
> 1, 2, 3

Good ideas. I'll implement that... With the changelog it's the same like with the blog, the user will get to the English page when visiting the changelog.

**Comment by pbek** [comment]
You could add a changelog menu item to the sidebar in your PR and remove the nav item for the Blog, like you suggested.

**Comment by noureddin** [comment]
Thank you! 😊

I merged your commits, and updated the PR:

1. I added the changelog to the sidebar, and used their translated names, with "(in English)". But I couldn't figure out how to make it just a link. Instead, I made it contain a single page, the English changelog page.
2. The Languages link was changed for English only. I propagated your change to the other languages.
3. I also included the RTL burger menu fix. 😇

But there is a problem: 

In the website that is deployed right now, English is fine, but other languages have all their pages being 404, except for the main pages being 403 (e.g., https://www.qownnotes.org/fr is 403 but https://www.qownnotes.org/fr/getting-started/markdown.html is 404 although the English https://www.qownnotes.org/getting-started/markdown.html exists).

**Comment by pbek** [comment]
LGTM, thank you!

**Comment by pbek** [comment]
> In the website that is deployed right now, English is fine, but other languages have all their pages being 404, except for the main pages being 403 (e.g., https://www.qownnotes.org/fr is 403 but https://www.qownnotes.org/fr/getting-started/markdown.html is 404 although the English https://www.qownnotes.org/getting-started/markdown.html exists).

Now that's strange, I'll have to look into that.

**Comment by pbek** [comment]
> Now that's strange, I'll have to look into that.

All seems to be fine again, I restarted to container.

**Pull request merged**
