### PR TITLE
Refactor notetextedit related stuff

### PR DESCRIPTION
**Pull request by Waqar144**
- Move all notetextedit related code to QOwnNotesMarkdownTextEdit
- Merge spellcheck context menu into the main one

### CODE REVIEW

**Comment by pbek** [comment]
Unfortunately breaking builds for older Qt versions. 😅 
https://build.opensuse.org/package/show/home:pbek:QOwnNotes/desktop

**Comment by Waqar144** [comment]
Easily fixable: just drop them.

**Comment by pbek** [comment]
@Waqar144, this PR broke the exporting the selected text (as preview or plain text) features. Now the whole document is exported instead of the selected text.

**Comment by pbek** [comment]
The same goes for "print selected text".

**Pull request merged**
