### PR TITLE
Enable aspell on linux build systems

### PR DESCRIPTION
**Pull request by Waqar144**

### CODE REVIEW

**Comment by pbek** [comment]
I keep my fingers crossed :grin:

**Comment by pbek** [comment]
Releasing now...

**Comment by Waqar144** [comment]
> Releasing now...

I have my eyes on OBS :eyes:

**Comment by pbek** [comment]
SLE doesn't find the aspell library...

**Comment by Waqar144** [comment]
> SLE doesn't find the aspell library...

I think the name for aspell there is `aspell-devel`

**Comment by pbek** [comment]
> I think there is no aspell dev library on SLE. 

Can you come up with a "if-clause" to don't fetch aspell for SLE?

**Comment by Waqar144** [comment]
Looking into it

**Pull request merged**
