### PR TITLE
Add tagging support for subfolders

### PR DESCRIPTION
**Pull request by cal2195**
This PR allows tags to function recursively in the selected folder and subfolders!

It works well on my system, with and without the "show subfolder notes" option in the settings! :)

### CODE REVIEW

**Comment by pbek** [comment]
You are changing a lot default behavior, I'm not sure how I should even test what side effects that has...

**Comment by cal2195** [comment]
Showing the notes tagged recursively was easy, the first commit!

The second commit is all just to show the count correctly - maybe there's a better way?

**Comment by cal2195** [comment]
I also the three functions aren't used anywhere else other than reloading the tag tree? :)

**Comment by pbek** [comment]
I'll need time to check all methods and what you are doing. And I'm currently pretty low on spare time. :/

**Comment by cal2195** [comment]
No problem! :)

Let me know if there's anything I should change!

**Comment by pbek** [comment]
I took it in. Suddenly had time to check the code due to a heavy thunderstorm that prevented me from working on my garden-door project. :)

**Comment by pbek** [comment]
It's far too complex to test all combination of settings, we'll see what will happen...

**Pull request merged**
