### PR TITLE
Use MainWindow::instance everywhere

### PR DESCRIPTION
**Pull request by Waqar144**
Also includes a fix for context menu positioning in a separate commit

Context menu positioning for preview and edit seem to be broken on wayland for some reason. Not sure why. Code looks correct

### CODE REVIEW

**Comment by pbek** [comment]
Thank you very much!

**Comment by pbek** [comment]
Ah, too early. It breaks the windows builds https://github.com/pbek/QOwnNotes/actions/runs/3336646627/jobs/5522049242

**Comment by pbek** [comment]
I fixed it

**Comment by Waqar144** [comment]
Thanks

**Pull request merged**
