### PR TITLE
Fix deselection of multi folder selection

### PR DESCRIPTION
**Pull request by Waqar144**
#327

### CODE REVIEW

**Comment by pbek** [comment]
Works great!

**Comment by pbek** [comment]
I was testing the multi-tag deselection. But your PR wasn't about that. :) Why does the the multi-tag deselection work now? :laughing:

**Comment by pbek** [comment]
Hm, and if I select one sub-folder. The tag multi-selection will be removed and only one tag will be selected.

**Comment by Waqar144** [comment]
> Hm, and if I select one sub-folder. The tag multi-selection will be removed and only one tag will be selected.

Ah yes, that's because tag tree is reloaded right after `filternotes`, 
There might be a way around that I think. 
But if you select multiple folders first and then select multiple tags, that works.

**Comment by Waqar144** [comment]
> I was testing the multi-tag deselection. But your PR wasn't about that. :) Why does the the multi-tag deselection work now? 😆

It was working previously, no? 🤔😅

**Comment by pbek** [comment]
Yes it does... I think I misread https://github.com/pbek/QOwnNotes/issues/327#issuecomment-562126920

**Comment by pbek** [comment]
I reverted this PR because of #1489.

**Pull request merged**
