### PR TITLE
Force usage of palette to ensure color is correct

### PR DESCRIPTION
**Pull request by Waqar144**
This should fix the colors hopefully. Not sure why they were appearing like that because I am also using dark theme.

### CODE REVIEW

**Comment by Waqar144** [comment]
This will address the empty actions and colors issues, hopefully. The empty items are probably the initial menu items I think.

**Comment by pbek** [comment]
> because I am also using dark theme

are you sure? or are you rather using KDE with a dark theme and that is inherited by QON?

**Comment by Waqar144** [comment]
> > because I am also using dark theme
> 
> are you sure? or are you rather using KDE with a dark theme and that is inherited by QON?

Hmm yes, I think that might be the reason.

Is the color okay with this change?

**Comment by Waqar144** [comment]
Also we can add more things to this, such as custom actions or actions that invoke a script or context menu actions / toolbar actions and so on.

**Comment by pbek** [comment]
> Is the color okay with this change?

It looks ok on my dark mode neon, need to test on my light mode neon

> Also we can add more things to this, such as custom actions or actions that invoke a script or context menu actions / toolbar actions and so on.

you mean like in the old dialog? yes, we need all the sub-items too again before we can roll out the new dialog! 😆

**Comment by Waqar144** [comment]
> you mean like in the old dialog? yes, we need all the sub-items too again before we can roll out the new dialog! laughing

Only the toolbar items are missing I think. Will add that.

**Comment by pbek** [comment]
> It looks ok on my dark mode neon, need to test on my light mode neon

looking good in dark mode on light mode kde neon!

**Pull request merged**
