### PR TITLE
Implement syntax highlighting in the preview

### PR DESCRIPTION
**Pull request by Waqar144**
#1480 
#1523 

- Most of the languages work except
  - YAML (doesn't work fully yet)
  - INI (Doesn't work fully yet)
  - CSS

### CODE REVIEW

**Comment by pbek** [comment]
Already the commit with the qmarkdowntextedit update failed: https://ci.appveyor.com/project/pbek/qownnotes/builds/29811407/job/m1knvbibksa8avue

**Comment by Waqar144** [comment]
Its the tests.

**Comment by pbek** [comment]
Those always... :grimacing:

**Comment by pbek** [comment]
I've to fix the cmake support.

**Pull request merged**
