### PR TITLE
logwidget: Use const refs for strings where possible

### PR DESCRIPTION
**Pull request by Waqar144**

### CODE REVIEW

**Comment by pbek** [comment]
Thank you for all the optimizations!

**Comment by Waqar144** [comment]
> Thank you for all the optimizations!

There's a lot more to come :laughing:

**Comment by Waqar144** [comment]
> Thank you for all the optimizations!

@pbek 
Have you looked into https://scan.coverity.com for static analysis? maybe linking it with Travis?

**Comment by pbek** [comment]
Thank you, I just submitted a build at https://scan.coverity.com/projects/pbek-qownnotes

**Comment by Waqar144** [comment]
> Thank you, I just submitted a build at https://scan.coverity.com/projects/pbek-qownnotes

I am watching it closely :wink:

**Comment by pbek** [comment]
Seems like there needs to be done more...

```
 Error details:
    invalid literal for int() with base 10: "tail: cannot open '/opt/workspace/pbek_QOwnNotes/cov-int/build-log.txt' for reading: No such file or directory"
    For more detail explanation on the error, please check: https://u2389337.ct.sendgrid.net/wf/click?upn=OgIsEqWzmIl4S-2FzEUMxLXL-2BukuZt9UUdRZhgmgzAKchwAzH1nH3073xDEXNRgHN6zzUI-2FRfbrE6mNOeeukHUQw-3D-3D_Bv5IPa4ZR8A8gQwUebUsVFBGJJTcqglj1IOC5gvCTJ8PD4thnjIImaGJyB2JktdEhB-2BkyDVo9azcAUuS4NKnIYrnulVIuKTBUYg04CdsSxus7Z2OjQ1Htp4uc1pjLc1-2FFgkb8kLfkNyUYOBmqHPzblG-2FQh6sCItSaI6tdGrX4zEgkjscFoVbP9mfSMruC44FQUZ3uOi7ewKkQVRb3zMyEj83NOC1M5AiOIswKYZirIA-3D

    If your build process isn't going smoothly, email us at scan-admin@coverity.com
    with your cov-int/build-log.txt file attached for assistance, or post your issue
    to the StackOverflow at https://u2389337.ct.sendgrid.net/wf/click?upn=OgIsEqWzmIl4S-2FzEUMxLXL-2BukuZt9UUdRZhgmgzAKchwAzH1nH3073xDEXNRgHN6zzUI-2FRfbrE6mNOeeukHUQw-3D-3D_Bv5IPa4ZR8A8gQwUebUsVFBGJJTcqglj1IOC5gvCTJ8PD4thnjIImaGJyB2JktdESLilon3RQKoa8Mrrk4UcwKZmexT9LZFPl6vDjmtQmD1gPHX-2FzHGBwMq2ynwOEyZup5BU6Tr0iTSfyKZqjXf6olk6gbPHnRatwiCtwoFGIssp1FcZTse-2Fb2GojbZPQFJyKMRYNpGtMIQ3jsKkaq17i8sYP6ZhkJpxhIparo7qy3w-3D
```

**Comment by Waqar144** [comment]
> Seems like there needs to be done more...
> 
> ```
>  Error details:
>     invalid literal for int() with base 10: "tail: cannot open '/opt/workspace/pbek_QOwnNotes/cov-int/build-log.txt' for reading: No such file or directory"
>     For more detail explanation on the error, please check: https://u2389337.ct.sendgrid.net/wf/click?upn=OgIsEqWzmIl4S-2FzEUMxLXL-2BukuZt9UUdRZhgmgzAKchwAzH1nH3073xDEXNRgHN6zzUI-2FRfbrE6mNOeeukHUQw-3D-3D_Bv5IPa4ZR8A8gQwUebUsVFBGJJTcqglj1IOC5gvCTJ8PD4thnjIImaGJyB2JktdEhB-2BkyDVo9azcAUuS4NKnIYrnulVIuKTBUYg04CdsSxus7Z2OjQ1Htp4uc1pjLc1-2FFgkb8kLfkNyUYOBmqHPzblG-2FQh6sCItSaI6tdGrX4zEgkjscFoVbP9mfSMruC44FQUZ3uOi7ewKkQVRb3zMyEj83NOC1M5AiOIswKYZirIA-3D
> 
>     If your build process isn't going smoothly, email us at scan-admin@coverity.com
>     with your cov-int/build-log.txt file attached for assistance, or post your issue
>     to the StackOverflow at https://u2389337.ct.sendgrid.net/wf/click?upn=OgIsEqWzmIl4S-2FzEUMxLXL-2BukuZt9UUdRZhgmgzAKchwAzH1nH3073xDEXNRgHN6zzUI-\
> ```

Yes seems like its not so straightforward as it seems. Also it isn't visible to me, says: "Not authorized to access this page"

**Comment by pbek** [comment]
I already tried to invite you. :)

**Comment by Waqar144** [comment]
> I already tried to invite you. :)

I think it will take a couple of days or more for me to able to see the project there cause they have to 'review' my association with the project

**Comment by pbek** [comment]
It says that "Waqar144" is a member.

**Comment by pbek** [comment]
Switched you to "Maintainer/Owner"

**Comment by pbek** [comment]
btw. I invited you with your publicly visible email address on GitHub

**Comment by Waqar144** [comment]
> btw. I invited you with your publicly visible email address on GitHub

Yes I got the email and was able to see the project in the dashboard.

**Comment by Waqar144** [comment]
> Switched you to "Maintainer/Owner"

Yes now i can see

**Comment by pbek** [comment]
Do your worst, Mr. CSCO (Chief Source Code Optimizer) :laughing:

**Comment by Waqar144** [comment]
haha, let's try to get it to build first. There are so many limitations.

**Pull request merged**
