### PR TITLE
Performance optimizations

### PR DESCRIPTION
**Pull request by Waqar144**
- Use QStringLiteral in note.cpp everywhere
- Use reserve to reserve memory before appending elements to `QLists` for better performance.

### CODE REVIEW

**Comment by pbek** [comment]
Awesome! You really take care of performance!

**Comment by Waqar144** [comment]
> Awesome! You really take care of performance!

Haha, I do. And the reasons are
- I have an older pc (2 core) :(
- Have seen a lot of users(including myself) abandon something just because it's slow
- And there's not much point in using c++ if we aren't faaaaaast. :grin:

**Comment by pbek** [comment]
> I have an older pc (2 core) :(

It's great to use older hardware for such things!

> Have seen a lot of users(including myself) abandon something just because it's slow

Which might rule out to use a fully fledged browser in QON. :grimacing: 

> And there's not much point in using c++ if we aren't faaaaaast. grin

in contrast to Electron apps :laughing:

**Comment by pbek** [comment]
> And there's not much point in using c++

but I'm a big Qt fanboy! :grin:

**Comment by Waqar144** [comment]
> > And there's not much point in using c++
> 
> but I'm a big Qt fanboy! grin

Me too :rofl:

> Which might rule out to use a fully fledged browser in QON. grimacing

With syntax highlighting, we are feature complete so in my opinion, a person doesn't even need to go to preview. Everything is being rendered correctly in the text editor :grin:

**Comment by pbek** [comment]
> With syntax highlighting, we are feature complete so in my opinion, a person doesn't even need to go to preview. Everything is being rendered correctly in the text editor grin

True. But still the first thing that people ask me when they see your beautiful code block syntax highlighting is if it is possible to also have that in the preview. :grinning:

**Comment by Waqar144** [comment]
> > With syntax highlighting, we are feature complete so in my opinion, a person doesn't even need to go to preview. Everything is being rendered correctly in the text editor grin
> 
> True. But still the first thing that people ask me when they see your beautiful code block syntax highlighting is if it is possible to also have that in the preview. grinning

Yeah :grimacing: 
some day we'll have it there too maybe :grin: 

It wouldn't be slow. with QWebEngine... It would just take more memory

**Comment by pbek** [comment]
> It wouldn't be slow. with QWebEngine... It would just take more memory

Or we write our own markdown2html converter. :grin:

**Pull request merged**
