### PR TITLE
Small fix to documentation for `ScriptingService::jumpToNoteSubFolder()`.

### PR DESCRIPTION
**Pull request by sanderboom**
Real change is at line 672.  The rest is whitespace which vim automatically cleaned up. I'll revert that.

### CODE REVIEW

**Comment by pbek** [comment]
oh, thank you!

**Comment by pbek** [comment]
> The rest is whitespace which vim automatically cleaned up. I'll revert that.

You removed trailing whitespaces, right? It's ok, I don't like trailing whitespaces. ;)

**Comment by sanderboom** [comment]
Haha, me neither ;) For a moment I thought that removing trailing whitespace might have consequences like it would in markdown, but I'm happy their gone now ;)

**Comment by pbek** [comment]
Nah, all were in code blocks... :smile_cat:

**Pull request merged**
