### PR TITLE
Fix notes not visible when subfolders are off

### PR DESCRIPTION
**Pull request by Waqar144**
#1489

### CODE REVIEW

**Comment by pbek** [comment]
I think you pushed the reference to an older version of qmarkdowntextedit.

**Comment by Waqar144** [comment]
I did run git submodule update and pushed again. But it doesn't seem to change anything . What do I do?

**Comment by pbek** [comment]
Go into the qmarkdowntextedit directory and switch to the develop branch, then you can commit that in the QOwnNotes directory.

**Comment by pbek** [comment]
I'll do it for you. :)

**Comment by Waqar144** [comment]
> I'll do it for you. :)

Thanks :grimacing:

**Pull request merged**
