### PR TITLE
chore: Enable codeql action

### PR DESCRIPTION
**Pull request by naveensrinivasan**
This action runs GitHub's industry-leading semantic code analysis engine,
CodeQL, against a repository's source code to find security vulnerabilities.

https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/about-code-scanning-with-codeql

https://github.com/ossf/scorecard/blob/main/docs/checks.md#sast
Signed-off-by: naveensrinivasan <172697+naveensrinivasan@users.noreply.github.com>

### CODE REVIEW

**Comment by pbek** [comment]
It says `echo 'Semmle autobuild: no supported build system detected.'`, QOwnNotes uses qmake and cmake...

**Comment by naveensrinivasan** [comment]
> It says `echo 'Semmle autobuild: no supported build system detected.'`, QOwnNotes uses qmake and cmake...

There are options to override the build. 

Can you please let me know the build? I can update to override the build.

**Comment by naveensrinivasan** [comment]
> Thank you.
> Building on GitHub is done in https://github.com/pbek/QOwnNotes/blob/develop/.github/workflows/build-test.yml, but there is a lot of code in there to fetch the correct version of Qt for each operating system...

I wish there was one make file for linux to test this.

**Comment by pbek** [comment]
Building itself is very easy (see https://www.qownnotes.org/installation/building.html):

```shell
cd src
qmake
make
```

You just need to get Qt from somewhere first. That is what e.g. https://github.com/pbek/QOwnNotes/blob/d9302e198e612bb244e087735d3423ed889a4a42/.github/workflows/build-test.yml#L142-L147 is doing.

**Comment by pbek** [comment]
Still failing because of the auto-build...
https://github.com/pbek/QOwnNotes/runs/6469622196?check_suite_focus=true#step:5:175

**Comment by naveensrinivasan** [comment]
I am going to close it. Unless you want to address it.

**Comment by pbek** [comment]
I thought the only thing missing was the disabling of the autobuild feature of the action...

**Comment by naveensrinivasan** [comment]
Going to close this for now. Thanks

**Pull request closed without merging**
