### PR TITLE
Fix an optimization regression from #7848f4d

### PR DESCRIPTION
**Pull request by Waqar144**
Reviewed the whole commit again. Seems like everything was fixed last night except this one line.

### CODE REVIEW

**Comment by pbek** [comment]
Thank you! Was there no other file beside mainwindow.cpp?

**Comment by Waqar144** [comment]
> Thank you! Was there no other file beside mainwindow.cpp?

there was another file in that PR: `databaseservice.cpp`. I checked it as well. Seems good.

**Comment by pbek** [comment]
Great! And that commit was the only commit with (major) refactoring?

**Comment by Waqar144** [comment]
Yes. That has been the only commit with refactoring from my side till now.
You should review this change though, just to be sure:

https://github.com/pbek/QOwnNotes/blob/7848f4de14fd152be8a8ffc7c8d97f8f37d1a431/src/mainwindow.cpp#L1218-L1220

**Comment by pbek** [comment]
I wasn't sure about that one, but I let it in for now...

**Comment by Waqar144** [comment]
> I wasn't sure about that one, but I let it in for now...

The same thing is being checked inside the `setNoteTextFromNote(&currentNote, true);` function:

https://github.com/pbek/QOwnNotes/blob/be629652e1b831d42b61dc066f3d96b6729c01dc/src/mainwindow.cpp#L3997-L3998

So, theoretically it shouldn't cause any sort of problems.

**Comment by pbek** [comment]
Did you change those two lines?

**Comment by Waqar144** [comment]
> Did you change those two lines?

Nah. They are there.

**Pull request merged**
