### PR TITLE
Add ScriptingService method for creating subfolders

### PR DESCRIPTION
**Pull request by fnkabit**
I am currently working on #1165 and it would be required to create folders when importing notes.

### CODE REVIEW

**Comment by fnkabit** [comment]
@pbek Is there something wrong with the **ubuntu-latest 5.7 env** ?
```
2020-10-28 07:34:01,046 - aqt - ERROR - Download error: Symlink loop from '/home/runner/work/QOwnNotes/Qt/5.7/gcc_64/lib/libQt53DCore.so.5.7.1'
2020-10-28 07:34:02,456 - aqt - ERROR - Download error: [Errno 40] Too many levels of symbolic link
```

**Comment by pbek** [comment]
I restarted the jobs again.

**Comment by pbek** [comment]
I just saw `createNewNoteSubFolder` in `mainwindow` is already `Q_INVOKABLE`, so there is no need for a new scripting method.
It's also documented in https://www.qownnotes.org/scripting/classes.html#properties-and-methods-3.

**Comment by fnkabit** [comment]
Ah, sorry. Had the impression that all scripting methods should be available in `ScriptingService`. Will close PR.

**Comment by pbek** [comment]
> Had the impression that all scripting methods should be available in ScriptingService

It would be better to not expose more private API, but after writing too many wrapper for mainwindow methods I started to expose them directly 😁 since you have to mark those methods with `Q_INVOKABLE` it is at least clear that they are exposed...

**Comment by pbek** [comment]
If you want you can add a `::: tip` at https://www.qownnotes.org/scripting/methods-and-objects.html#jumping-to-a-note-subfolder telling people how to also create note subfolders.

**Comment by fnkabit** [comment]
> If you want you can add a `::: tip` at https://www.qownnotes.org/scripting/methods-and-objects.html#jumping-to-a-note-subfolder telling people how to also create note subfolders.

Good idea ! :+1: Thanks.

**Pull request closed without merging**
