### PR TITLE
Add code syntax coloring options to settings

### PR DESCRIPTION
**Pull request by Waqar144**

### CODE REVIEW

**Comment by pbek** [comment]
I guess the other schemata would also need those colors. :grimacing:

**Comment by Waqar144** [comment]
> I guess the other schemata would also need those colors. grimacing

Yeah :grimacing:

**Comment by Waqar144** [comment]
5 done

**Comment by pbek** [comment]
The schema "Light" also code colors which background, was that on purpose?

**Comment by pbek** [comment]
If you want you can change the general colors for code blocks also away from green. :grin:

**Comment by pbek** [comment]
3) JS "support" isn't done yet, right? looks a bit funny with the white function declaration. :grin: 

image

**Comment by Waqar144** [comment]
>     1. The schema "Light" also code colors with background, was that on purpose?

I am just copying the background color of `codeblock` so that it looks uniform

**Comment by Waqar144** [comment]
>     1. JS "support" isn't done yet, right? looks a bit funny with the white function declaration. grin
> 


That's a bug. Fixing

**Pull request merged**
