### PR TITLE
first commit to Chinese translation

### PR DESCRIPTION
**Pull request by LiangWei88**
All the texts are translated

### CODE REVIEW

**Comment by pbek** [comment]
looking very good, I will test it now

**Comment by pbek** [comment]
Just awesome! Thanks a lot for your great work! :+1:

**Comment by LiangWei88** [comment]
I saw there is one test is not passed.
I did something wrong?

**Comment by pbek** [comment]
No, just a problem with Travis CI... I hope it is gone by tomorrow...

**Pull request merged**
