### PR TITLE
MD4C testing only

### PR DESCRIPTION
**Pull request by Waqar144**

### CODE REVIEW

**Comment by Waqar144** [comment]
ah, the test are failing...

**Comment by Waqar144** [comment]
You can check the difference in performance with the note I gave you before (the huge note with lots of headings).

MD4C will be instant. Hoedown slows down quite a bit.

**Comment by pbek** [comment]
Ah, cmake support is broken, right?

**Comment by pbek** [comment]
And could you please update the PR with the latest changes. :grin: 

Checkbox lists doesn't seem to work in the preview.

**Comment by pbek** [comment]
I created a new branch `md4c` could you please make your PR against that branch. Then I can accept and also work on it.

**Comment by Waqar144** [comment]
> Ah, cmake support is broken, right?

Yeah 😬

**Comment by Waqar144** [comment]
Would you prefer to use the library as submodule or have our own fork of it?

**Comment by pbek** [comment]
> Would you prefer to use the library as submodule or have our own fork of it?

Since you want to work on it I guess we should make a fork from https://github.com/mity/md4c in https://github.com/qownnotes and use it as git sub-module.

**Comment by pbek** [comment]
I've forked to https://github.com/qownnotes/md4c and made you admin.

**Comment by pbek** [comment]
If you would create a PR to the new branch I can help with the sub-module.

**Comment by Waqar144** [comment]
> If you would create a PR to the new branch I can help with the sub-module.

I already did. Its now pushing to `md4c` branch

**Comment by pbek** [comment]
> I already did. Its now pushing to md4c branch

did you create a create a PR for that?

**Comment by Waqar144** [comment]
> > I already did. Its now pushing to md4c branch
> 
> did you create a create a PR for that?

No, i just changed the base of this one from `develop` to `md4c`. That should work, right?

**Comment by pbek** [comment]
> No, i just changed the base of this one from develop to md4c. That should work, right?

Ah, yes, it does. But I cannot merge it because of the conflicts.

**Comment by Waqar144** [comment]
I will create a new one. This one is too messy.

**Pull request closed without merging**
