### PR TITLE
Add table content alignment in note edit panel

### PR DESCRIPTION
**Pull request by fnkabit**
Implements #1905 
Video demo: https://youtu.be/qTzo4J0clmY

### CODE REVIEW

**Comment by pbek** [comment]
Hey, awesome... But I got a crash when trying to press Ctrl + Space in 

```markdown
|        |             |        |
| ------ | ---:        | ------ |
| 1      | 1           | 1      |
| 2      | 2           | 2      |
| 4      | 3           | 3      |
| longer | longer      | longer |
| longer | even longer | longer |
```

```
__GI_raise 0x00007f9e9031a18b
__GI_abort 0x00007f9e902f9859
qt_message_fatal 0x00007f9e908a5c39
QMessageLogger::fatal 0x00007f9e908a5c39
qt_assert_x 0x00007f9e908a5042
QVector<Qt::AlignmentFlag>::at qvector.h:455
Utils::Gui::autoFormatTableAtCursor gui.cpp:614
MainWindow::on_actionAutocomplete_triggered mainwindow.cpp:9798
MainWindow::qt_static_metacall moc_mainwindow.cpp:1180
MainWindow::qt_metacall moc_mainwindow.cpp:1390
doActivate<false> atomic_base.h:734
QAction::triggered(bool) 0x00007f9e917c07f6
QAction::activate(QAction::ActionEvent) 0x00007f9e917c2ec8
QAction::event(QEvent*) 0x00007f9e917c37df
QApplicationPrivate::notify_helper(QObject*, QEvent*) 0x00007f9e917c6cc3
QApplication::notify(QObject*, QEvent*) 0x00007f9e917cfc70
QCoreApplication::notifyInternal2 0x00007f9e90ac36aa
QShortcutMap::dispatchEvent(QKeyEvent*) 0x00007f9e90f21653
QShortcutMap::tryShortcut(QKeyEvent*) 0x00007f9e90f21ff3
QWindowSystemInterface::handleShortcutEvent(QWindow*, unsigned long, int, QFlags<Qt::KeyboardModifier>, unsigned int, unsigned int, unsigned int, QString const&, bool, unsigned short) 0x00007f9e90ecf7a2
QGuiApplicationPrivate::processKeyEvent(QWindowSystemInterfacePrivate::KeyEvent*) 0x00007f9e90eef311
QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) 0x00007f9e90ef459b
QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) 0x00007f9e90ecc2cb
<unknown> 0x00007f9e8d0f999e
g_main_context_dispatch 0x00007f9e8f999fbd
<unknown> 0x00007f9e8f99a240
g_main_context_iteration 0x00007f9e8f99a2e3
QEventDispatcherGlib::processEvents 0x00007f9e90b1de92
QEventLoop::exec 0x00007f9e90ac21bb
QCoreApplication::exec 0x00007f9e90aca354
main main.cpp:619
__libc_start_main 0x00007f9e902fb0b3
_start 0x0000556dd0fd141e
```

**Comment by fnkabit** [comment]
Thanks @pbek ; I believe this last commit should fix it.

**Comment by pbek** [comment]
It does, really awesome. Works like a charm. Even centering! Thank you very much!

**Comment by fnkabit** [comment]
Glad it worked.
Thanks for the great app !

**Comment by pbek** [comment]
Thank you for your help and your kind words!

**Comment by pbek** [comment]
Feel encouraged to also work on other feature requests or bugs. 😁

**Comment by fnkabit** [comment]
@pbek Thank you. Really looking forward to it.

**Comment by pbek** [comment]
Just let me know if you need some help!

**Pull request merged**
