### PR TITLE
Use QStringLiteral instead of normal string literals

### PR DESCRIPTION
**Pull request by Waqar144**
- Using `QStringLiteral` instead of string literals to create `QString` at compile time to reduce runtime overhead of QString creation and copy. Improves performance [WIP]
 - Prevent useless calls to `setNoteTextFromNote()` from `updatePanelMenu()` when note preview widget is not visible

### CODE REVIEW

**Comment by pbek** [comment]
Nice work!

**Comment by pbek** [comment]
Haha, but your PR completely broke my un-commited changes.

**Comment by Waqar144** [comment]
> Haha, but your PR completely broke my un-commited changes.

Hope it wasn't too bad :laughing: 

Note loading performance has increased a lot. The same note which was loading in 1000ms is now loading in 390ms~

**Comment by pbek** [comment]
Wow, that's awesome!

**Pull request merged**
