### PR TITLE
Fix typos in trash dialogs

### PR DESCRIPTION
**Pull request by smokris**

### CODE REVIEW

**Comment by pbek** [comment]
thx

**Comment by pbek** [comment]
can you please make the pull request to `develop`, master is just for releases

**Comment by smokris** [comment]
Sure, I just changed it.

**Comment by pbek** [comment]
thank you

**Comment by pbek** [comment]
## 19.1.1
- fixed some typos in the *Trash dialog* (thank you @smokris)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by smokris** [comment]
I just installed 19.1.1.  Looks good.  Thanks.

**Comment by pbek** [comment]
Great, thank you for testing!

**Pull request merged**
