### PR TITLE
Fix French translation for import/export settings

### PR DESCRIPTION
**Pull request by Baptistou**

### CODE REVIEW

**Comment by pbek** [comment]
Thank you for your concern! But this file will be overwritten by Crowdin.
Can you please propose your changes in https://crowdin.com/translate/qownnotes/1/en-fr directly.

See https://www.qownnotes.org/contributing/translation.html

**Comment by pbek** [comment]
Meanwhile I'll close this PR.

**Comment by Baptistou** [comment]
Ok my bad ^^ I proposed these changes on Crowdin.

**Comment by pbek** [comment]
Thank you! 😉

**Pull request closed without merging**
