### PR TITLE
Remove broken note links check to improve performance

### PR DESCRIPTION
**Pull request by Waqar144**
This check is now slowing down performance a lot so I am removing it. Note loading speed should increase a lot now, especially for notes larger than 200 lines.

### CODE REVIEW

**Comment by pbek** [comment]
But this breaks current functionality. If you want you can create a setting to disable those checks.

**Comment by Waqar144** [comment]
Which functionality will it break? 🤔
This is just an extra check, that's unnecessary now.

**Comment by pbek** [comment]
> that's unnecessary now.

where is the broken note links highlighting done otherwise?

**Comment by Waqar144** [comment]
> where is the broken note links highlighting done otherwise?

The actual highlighting function is still in the highlighter. 

This was just a precheck we were doing on the whole document before loading it and  checking whether broken note link highlighting was required or not. Then our note loading speed was much slower so it was beneficial. Now we are much faster, so this check is slowing things down.

**Comment by pbek** [comment]
Sorry, I didn't read the code well enough, I just read "Remove broken note links check" and saw code was being removed from the highlighter. :smile:

**Comment by Waqar144** [comment]
> Sorry, I didn't read the code well enough, I just read "Remove broken note links check" and saw code was being removed from the highlighter. smile

:laughing:

**Pull request merged**
