### PR TITLE
Raise warning levels + update to use C++ 17

### PR DESCRIPTION
**Pull request by Waqar144**
- Raise warning levels + error out on warning to force us to not leave any warnings or deprecated stuff around
- Use C++ 17, 2022 is here so time to update + Qt6 requires C++17

Needs qmarkdowntextedit https://github.com/pbek/qmarkdowntextedit/pull/154

### CODE REVIEW

**Comment by pbek** [comment]
> Needs qmarkdowntextedit pbek/qmarkdowntextedit#154

I tested with this PR, but I got build errors (using cmake):

```
/home/omega/Code/_internal/QOwnNotes/src/entities/notefolder.cpp:512:2: error: extra ‘;’ [-Werror=pedantic]
  512 | };
      |  ^
cc1plus: all warnings being treated as errors
make[3]: *** [CMakeFiles/QOwnNotes.dir/build.make:1140: CMakeFiles/QOwnNotes.dir/entities/notefolder.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
In file included from /home/omega/Code/_internal/QOwnNotes/src/cmake-build-debug/QOwnNotes_autogen/6GK57LHRIU/../../../libraries/qkeysequencewidget/qkeysequencewidget/src/qkeysequencewidget_p.h:54,
                 from /home/omega/Code/_internal/QOwnNotes/src/cmake-build-debug/QOwnNotes_autogen/6GK57LHRIU/moc_qkeysequencewidget_p.cpp:10,
                 from /home/omega/Code/_internal/QOwnNotes/src/cmake-build-debug/QOwnNotes_autogen/mocs_compilation.cpp:39:
/home/omega/Code/_internal/QOwnNotes/src/cmake-build-debug/QOwnNotes_autogen/6GK57LHRIU/../../../libraries/qkeysequencewidget/qkeysequencewidget/src/qkeysequencewidget.h:82:42: error: extra ‘;’ [-Werror=pedantic]
   82 |     Q_DECLARE_PRIVATE(QKeySequenceWidget);
      |                                          ^
      |                                          -
/home/omega/Code/_internal/QOwnNotes/src/cmake-build-debug/QOwnNotes_autogen/6GK57LHRIU/../../../libraries/qkeysequencewidget/qkeysequencewidget/src/qkeysequencewidget.h:123:50: error: extra ‘;’ [-Werror=pedantic]
  123 |     Q_DECLARE_FLAGS(ClearButtonShow, ClearButton);
      |                                                  ^
      |                                                  -
In file included from /home/omega/Code/_internal/QOwnNotes/src/cmake-build-debug/QOwnNotes_autogen/6GK57LHRIU/moc_qkeysequencewidget_p.cpp:10,
                 from /home/omega/Code/_internal/QOwnNotes/src/cmake-build-debug/QOwnNotes_autogen/mocs_compilation.cpp:39:
/home/omega/Code/_internal/QOwnNotes/src/cmake-build-debug/QOwnNotes_autogen/6GK57LHRIU/../../../libraries/qkeysequencewidget/qkeysequencewidget/src/qkeysequencewidget_p.h:62:41: error: extra ‘;’ [-Werror=pedantic]
   62 |     Q_DECLARE_PUBLIC(QKeySequenceWidget);
      |                                         ^
      |                                         -
cc1plus: all warnings being treated as errors
make[3]: *** [CMakeFiles/QOwnNotes.dir/build.make:659: CMakeFiles/QOwnNotes.dir/QOwnNotes_autogen/mocs_compilation.cpp.o] Error 1
In file included from /home/omega/Code/_internal/QOwnNotes/src/libraries/qkeysequencewidget/qkeysequencewidget/src/qkeysequencewidget.h:46,
                 from /home/omega/Code/_internal/QOwnNotes/src/dialogs/settingsdialog.cpp:9:
/home/omega/Code/_internal/QOwnNotes/src/libraries/qkeysequencewidget/qkeysequencewidget/src/qkeysequencewidget_p.h:62:41: error: extra ‘;’ [-Werror=pedantic]
   62 |     Q_DECLARE_PUBLIC(QKeySequenceWidget);
      |                                         ^
      |                                         -
In file included from /home/omega/Code/_internal/QOwnNotes/src/dialogs/settingsdialog.cpp:9:
/home/omega/Code/_internal/QOwnNotes/src/libraries/qkeysequencewidget/qkeysequencewidget/src/qkeysequencewidget.h:82:42: error: extra ‘;’ [-Werror=pedantic]
   82 |     Q_DECLARE_PRIVATE(QKeySequenceWidget);
      |                                          ^
      |                                          -
/home/omega/Code/_internal/QOwnNotes/src/libraries/qkeysequencewidget/qkeysequencewidget/src/qkeysequencewidget.h:123:50: error: extra ‘;’ [-Werror=pedantic]
  123 |     Q_DECLARE_FLAGS(ClearButtonShow, ClearButton);
      |                                                  ^
      |                                                  -
cc1plus: all warnings being treated as errors
make[3]: *** [CMakeFiles/QOwnNotes.dir/build.make:737: CMakeFiles/QOwnNotes.dir/dialogs/settingsdialog.cpp.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:189: CMakeFiles/QOwnNotes.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:196: CMakeFiles/QOwnNotes.dir/rule] Error 2
make: *** [Makefile:182: QOwnNotes] Error 2
```

in qtcreator with qmake I get more error than I can post here 😅

**Comment by Waqar144** [comment]
> > Needs qmarkdowntextedit [pbek/qmarkdowntextedit#154](https://github.com/pbek/qmarkdowntextedit/pull/154)
> 
> I tested with this PR, but I got build errors (using cmake):
> 
> ```
> /home/omega/Code/_internal/QOwnNotes/src/entities/notefolder.cpp:512:2: error: extra ‘;’ [-Werror=pedantic]
>   512 | };
>       |  ^
> cc1plus: all warnings being treated as errors
> make[3]: *** [CMakeFiles/QOwnNotes.dir/build.make:1140: CMakeFiles/QOwnNotes.dir/entities/notefolder.cpp.o] Error 1
> make[3]: *** Waiting for unfinished jobs....
> In file included from /home/omega/Code/_internal/QOwnNotes/src/cmake-build-debug/QOwnNotes_autogen/6GK57LHRIU/../../../libraries/qkeysequencewidget/qkeysequencewidget/src/qkeysequencewidget_p.h:54,
>                  from /home/omega/Code/_internal/QOwnNotes/src/cmake-build-debug/QOwnNotes_autogen/6GK57LHRIU/moc_qkeysequencewidget_p.cpp:10,
>                  from /home/omega/Code/_internal/QOwnNotes/src/cmake-build-debug/QOwnNotes_autogen/mocs_compilation.cpp:39:
> /home/omega/Code/_internal/QOwnNotes/src/cmake-build-debug/QOwnNotes_autogen/6GK57LHRIU/../../../libraries/qkeysequencewidget/qkeysequencewidget/src/qkeysequencewidget.h:82:42: error: extra ‘;’ [-Werror=pedantic]
>    82 |     Q_DECLARE_PRIVATE(QKeySequenceWidget);
>       |                                          ^
>       |                                          -
> /home/omega/Code/_internal/QOwnNotes/src/cmake-build-debug/QOwnNotes_autogen/6GK57LHRIU/../../../libraries/qkeysequencewidget/qkeysequencewidget/src/qkeysequencewidget.h:123:50: error: extra ‘;’ [-Werror=pedantic]
>   123 |     Q_DECLARE_FLAGS(ClearButtonShow, ClearButton);
>       |                                                  ^
>       |                                                  -
> In file included from /home/omega/Code/_internal/QOwnNotes/src/cmake-build-debug/QOwnNotes_autogen/6GK57LHRIU/moc_qkeysequencewidget_p.cpp:10,
>                  from /home/omega/Code/_internal/QOwnNotes/src/cmake-build-debug/QOwnNotes_autogen/mocs_compilation.cpp:39:
> /home/omega/Code/_internal/QOwnNotes/src/cmake-build-debug/QOwnNotes_autogen/6GK57LHRIU/../../../libraries/qkeysequencewidget/qkeysequencewidget/src/qkeysequencewidget_p.h:62:41: error: extra ‘;’ [-Werror=pedantic]
>    62 |     Q_DECLARE_PUBLIC(QKeySequenceWidget);
>       |                                         ^
>       |                                         -
> cc1plus: all warnings being treated as errors
> make[3]: *** [CMakeFiles/QOwnNotes.dir/build.make:659: CMakeFiles/QOwnNotes.dir/QOwnNotes_autogen/mocs_compilation.cpp.o] Error 1
> In file included from /home/omega/Code/_internal/QOwnNotes/src/libraries/qkeysequencewidget/qkeysequencewidget/src/qkeysequencewidget.h:46,
>                  from /home/omega/Code/_internal/QOwnNotes/src/dialogs/settingsdialog.cpp:9:
> /home/omega/Code/_internal/QOwnNotes/src/libraries/qkeysequencewidget/qkeysequencewidget/src/qkeysequencewidget_p.h:62:41: error: extra ‘;’ [-Werror=pedantic]
>    62 |     Q_DECLARE_PUBLIC(QKeySequenceWidget);
>       |                                         ^
>       |                                         -
> In file included from /home/omega/Code/_internal/QOwnNotes/src/dialogs/settingsdialog.cpp:9:
> /home/omega/Code/_internal/QOwnNotes/src/libraries/qkeysequencewidget/qkeysequencewidget/src/qkeysequencewidget.h:82:42: error: extra ‘;’ [-Werror=pedantic]
>    82 |     Q_DECLARE_PRIVATE(QKeySequenceWidget);
>       |                                          ^
>       |                                          -
> /home/omega/Code/_internal/QOwnNotes/src/libraries/qkeysequencewidget/qkeysequencewidget/src/qkeysequencewidget.h:123:50: error: extra ‘;’ [-Werror=pedantic]
>   123 |     Q_DECLARE_FLAGS(ClearButtonShow, ClearButton);
>       |                                                  ^
>       |                                                  -
> cc1plus: all warnings being treated as errors
> make[3]: *** [CMakeFiles/QOwnNotes.dir/build.make:737: CMakeFiles/QOwnNotes.dir/dialogs/settingsdialog.cpp.o] Error 1
> make[2]: *** [CMakeFiles/Makefile2:189: CMakeFiles/QOwnNotes.dir/all] Error 2
> make[1]: *** [CMakeFiles/Makefile2:196: CMakeFiles/QOwnNotes.dir/rule] Error 2
> make: *** [Makefile:182: QOwnNotes] Error 2
> ```
> 
> in qtcreator with qmake I get more error than I can post here sweat_smile

exactly. There are two objectives with this PR
- Fix all warnings everywhere and never allow warnings in main branch
- Ensure we can compile on all platforms with C++17
- Once warnings are fixed and C++17 works, road to Qt6 will also be a bit easier

There are some warnings that I haven't enabled yet, but will enable in steps

**Comment by Waqar144** [comment]
Okay, sent patches for qtcsv and qkeysequencewidget

**Comment by Waqar144** [comment]
should build with Qt6 now (once submodules PRs are merged)

**Comment by Waqar144** [comment]
Qt 6 will need to be bumped to 6.2.2

**Comment by pbek** [comment]
> should build with Qt6 now (once submodules PRs are merged)

they should be merged

> Qt 6 will need to be bumped to 6.2.2

I bumped it

**Comment by Waqar144** [comment]
Websockets module isn't there for some reason even though its available wtih 6.2.2, that is needed to build. Will we need to add it explicitly?

**Comment by pbek** [comment]
> Websockets module isn't there for some reason even though its available wtih 6.2.2, that is needed to build. Will we need to add it explicitly?

https://github.com/jurplel/install-qt-action#modules says you can install modules.
I tried with https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt6_622/qt.qt6.622.addons.qtwebsockets/ in https://github.com/pbek/QOwnNotes/commit/cbbd3b0d2e4979cfc22fec5403c461cc9b63db2a. Does that help?

**Comment by Waqar144** [comment]
> > Websockets module isn't there for some reason even though its available wtih 6.2.2, that is needed to build. Will we need to add it explicitly?
> 
> https://github.com/jurplel/install-qt-action#modules says you can install modules. I tried with https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt6_622/qt.qt6.622.addons.qtwebsockets/ in [cbbd3b0](https://github.com/pbek/QOwnNotes/commit/cbbd3b0d2e4979cfc22fec5403c461cc9b63db2a). Does that help?

let me rebase, should hopefully work now.

**Comment by Waqar144** [comment]
Still fails to find `websockets` for some reason: `Project ERROR: Unknown module(s) in QT: websockets`

**Comment by pbek** [comment]
https://github.com/pbek/QOwnNotes/runs/4947652048?check_suite_focus=true#step:10:318 says at least it was supposed to be installed, but then it says `Some of specified modules are unknown.`. Maybe it has a different name?

**Comment by Waqar144** [comment]
Module name seems to be correct according to aqtinstall docs. It also says:

```
Specified Qt version is unknown: 6.2.2.
```

So maybe, it needs to be 6.2 like before.

**Comment by pbek** [comment]
> So maybe, it needs to be 6.2 like before.

Want me to change it back to 6.2? Or to 6.3?

**Comment by Waqar144** [comment]
6.2, 6.3 is not out yet I think

**Comment by pbek** [comment]
> 6.2, 6.3 is not out yet I think

I did.

And I did get some other build errors at the snapcraft build:
https://github.com/pbek/QOwnNotes/runs/4948781480?check_suite_focus=true#step:16:4854

**Comment by Waqar144** [comment]
> > 6.2, 6.3 is not out yet I think
> 
> I did.

Modified it `6.2.0` as `6.2` doesn't seem to work.
 
> And I did get some other build errors at the snapcraft build: https://github.com/pbek/QOwnNotes/runs/4948781480?check_suite_focus=true#step:16:4854

That's a moc issue and unrelated to this. The build is succeeding there as you can see under Build QOwnNotes, but probably during the second build moc failed at something. So, I think its best to run `make clean` before starting the second build.

**Comment by pbek** [comment]
I don't know what is causing it, but at least https://github.com/pbek/QOwnNotes/runs/4949984183?check_suite_focus=true runs through...

I'll try a `make clean`, good idea!

**Comment by Waqar144** [comment]
I have enabled `Werror` for only `DEV_MODE` builds now, which is meant for developers and github CI. For the rest, it should be same as before.

**Comment by Waqar144** [comment]
Also, maybe I am wrong but seems like `qtwebsockets` isn't there in `aqtinstall`: https://github.com/miurahr/aqtinstall/blob/08b66255cb184e132112350601b1547f9f4e6910/aqt/combinations.json

**Comment by pbek** [comment]
> Also, maybe I am wrong but seems like qtwebsockets isn't there in aqtinstall: https://github.com/miurahr/aqtinstall/blob/08b66255cb184e132112350601b1547f9f4e6910/aqt/combinations.json

Strange

**Comment by Waqar144** [comment]
All green now. (Except for Qt6)

**Comment by Waqar144** [comment]
Qt6 is building now + all the other ones. Windows and mac fails, but can't fix those since only trusted people can update the Qhotkey submodule and make all builds pass. This is all for this PR from my side.

**Pull request merged**
