### PR TITLE
in this PR I fixed bug #63 

### PR DESCRIPTION
**Pull request by wexaadev**

### CODE REVIEW

**Comment by pbek** [comment]
I'm sorry, issue #63 was already fixed and confirmed as fixed yesterday.

**Comment by pbek** [comment]
Thank you for your effort, I think it would be sensible to announce that you want to work on an issue. :+1: :smile_cat:

**Comment by pbek** [comment]
And please always make sure your fork is up-to-date before creating a pull request, otherwise GitHub will not let me merge it.

**Comment by wexaadev** [comment]
hmmmmm ok and thanks for your supporting

**Comment by pbek** [comment]
You can also subscribe an issue, even if you didn't comment on it. This way you will get notifications if anyone comments on it or if it gets closed.

**Pull request closed without merging**
