### PR TITLE
Use parent class highlightMarkdown method

### PR DESCRIPTION
**Pull request by Waqar144**
This is redundant, I think its better to use the parent class method directly.

### CODE REVIEW

**Comment by pbek** [comment]
Does this also already fix #1558?

**Comment by Waqar144** [comment]
> Does this also already fix #1558?

The library still needs to be updated. But with this change we don't have to worry about updating QON everytime the lib changes

**Comment by pbek** [comment]
I updated the library. Highlighting works now. One interesting aspect with dark schema (light schema seems ok). Strings have no background color. :grin: In the fenced code blocks they have the background color if the code block.

image

    <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
    <verzeichnis>
         <titel>Wikipedia Städteverzeichnis</titel>
         <eintrag>
              <stichwort>Genf</stichwort>
              <eintragstext>Genf ist der Sitz von ...</eintragstext>
         </eintrag>
         <eintrag>
              <stichwort>Köln</stichwort>
              <eintragstext>Köln ist eine Stadt, die ...</eintragstext>
         </eintrag>
    </verzeichnis>

**Comment by Waqar144** [comment]
Will fix that.
However it can kind of fixed if you turn of code block bg color off ;)

**Comment by Waqar144** [comment]
We can't draw rectangles on this. Two solutions:
1. We lose the syntax highlighting in it.
2. Turn off code block background (or alternatively turn on background for all elements of type code)

**Comment by pbek** [comment]
I vote for 1) since the type can't be specified and so there is no context. `"` doesn't always mean "string"

**Comment by Waqar144** [comment]
Alright, will do that.

**Comment by Waqar144** [comment]
Try now

**Comment by pbek** [comment]
Works great, thank you!

**Pull request merged**
