### PR TITLE
Fixed failing to import notes from an existing note folder via the welcome dialog

### PR DESCRIPTION
**Pull request by liulex**
Steps to reproduce the bug is described in: https://github.com/pbek/QOwnNotes/issues/1140#issuecomment-461753634
Only tested in portable mode with no cloud setup.

### CODE REVIEW

**Comment by pbek** [comment]
Looking good too, thank you!

**Comment by pbek** [comment]
Currently the app seems to be crashing in portable mode on first start after the welcome dialog (testen on Linux and macOS) :/

**Comment by pbek** [comment]
launching a 2nd seems to be working

**Comment by pbek** [comment]
sorry, that's #1146

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by liulex** [comment]
Yes, it works perfectly for me. :)

**Pull request merged**
