### PR TITLE
Add Two Dark color scheme

### PR DESCRIPTION
**Pull request by ScottKillen**
Add the correct schema this time. :/

2020-01-07 10_58_55-Welcome to QOwnNotes - QOwnNotes 20 1 3

### CODE REVIEW

**Comment by pbek** [comment]
Great, thank you for the addition!

**Comment by pbek** [comment]
## 20.1.5
- added a **new editor color schema** *Two Dark* by @ScottKillen

There now is a new release, could you please test it and report if it works for you?

**Comment by ScottKillen** [comment]
It works like a charm.

**Comment by pbek** [comment]
Great, thank you for testing!

**Pull request merged**
