### PR TITLE
Enhanced Text case toggle 

### PR DESCRIPTION
**Pull request by schittli**
Text case toggle now automatically select the word under the cursor, if no text was selected.
Additionally, the original Cursor- and Text-Selection is restored.

### CODE REVIEW

**Comment by pbek** [comment]
Looking good. Thanks a lot. Will be in the next release in a bit.

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by schittli** [comment]
Thanks a lot :-),
Hmmm... where should I get the release from?
I've seen Linux and MacOS releases, but I can only test Windows and [there is no new Windows release](https://github.com/pbek/QOwnNotes/releases).
Or should I copy the Source and rebuild it?

**Comment by pbek** [comment]
There was a problem in the AppVeyor config, so it didn't get release. Should be published soon now.
https://ci.appveyor.com/project/pbek/qownnotes/build/windows-b3535/job/fwjuiqsbc8lxik3k

**Comment by schittli** [comment]
It's great that you know the build process :-), I downloaded and tested the small modification and it worked perfectly. Thanks a lot!

**Comment by pbek** [comment]
Thank you for testing! :)

**Pull request merged**
