### PR TITLE
Update translation.md

### PR DESCRIPTION
**Pull request by Fabijenna**
added point 9)

### CODE REVIEW

**Comment by pbek** [comment]
Don't you also find those bullet points 1..9 distracting with all the text and screenshots between them?

Maybe it's time to switch to h3 headlines (`### Headline text`) for each of the 9 blocks instead... They would also get an anchor then, which could be referenced in an URL to directly point to them.

What do you think?

**Comment by Fabijenna** [comment]
> Don't you also find those bullet points 1..9 distracting with all the text and screenshots between them?
> 
> Maybe it's time to switch to h3 headlines (`### Headline text`) for each of the 9 blocks instead... They would also get an anchor then, which could be referenced in an URL to directly point to them.
> 
> What do you think?

Sounds legit! Let's do that.

**Comment by pbek** [comment]
Should I close this PR and you open another one or do you want to edit this one?

**Comment by Fabijenna** [comment]
It doesn't matter to me, there is nothing won with another PR, is there? I will continue working on this PR.

**Comment by pbek** [comment]
Ok

**Comment by Fabijenna** [comment]
where can I see the output of my latest request? (or the input)

**Comment by Fabijenna** [comment]
Found it.

**Comment by Fabijenna** [comment]
Well I need it merged but the actual translation is not uploaded, so I need to know where to start.

**Comment by Fabijenna** [comment]
Please merge first.

**Comment by pbek** [comment]
If I merge this PR you cannot add stuff to it any more. You need to edit the file in your branch of your fork: https://github.com/Fabijenna/QOwnNotes/blob/patch-20/webpage/src/contributing/translation.md
The changes will automatically be added to this PR.

**Comment by Fabijenna** [comment]
Actually i don't  really find them annoying, it's just as it is. If you remove the screenshots, your taking away people one sense to use for orientation.

I don't know what you mean. 

Please do it yourself because I gotta blast. 

Check the newest update because I changed more than point nine and it's relevant.

**Comment by pbek** [comment]
I never was talking about removing the screenshots.
It's just about that ordered lists were misused and now one more point is added to the mess. 😅

**Comment by pbek** [comment]
And there are several typos on the page. 😅

**Comment by pbek** [comment]
Much clearer now...
https://github.com/pbek/QOwnNotes/blob/develop/webpage/src/contributing/translation.md#general-tips

**Comment by Fabijenna** [comment]
Now that's better then, that you've finished it, I didn't understand well what you wanted, and I felt that you have a clear picture and as I'm not very experienced with Markdown I felt that it's better you do it.

Moreover I waited 1 hour for any response and then my battery was empty and it takes a few hours to load.

BTW I don't find typos very funny, I'd surely delete them if I had worked on the task.

**Comment by Fabijenna** [comment]
Oh it really looks great! 

You've such an eye for great design! 

👏🏽 

And sorry I didn't see your comment before I answered. 

Slightly stressed out, sry.

**Comment by pbek** [comment]
> BTW I don't find typos very funny, I'd surely delete them if I had worked on the task.

https://github.com/pbek/QOwnNotes/commit/bcdcb9ea1de0e6b539e7973246d69ccd4be3a652

> You've such an eye for great design!

Nah, my tiny brain just needs more structure and smaller blocks to grasp so much information.

Plus you now can link directly to a block, e.g. https://www.qownnotes.org/contributing/translation.html#variables
That makes it easier to point translators into the right direction, when they are asking about something.

**Pull request merged**
