### PR TITLE
Make db non const when querying

### PR DESCRIPTION
**Pull request by Waqar144**

### CODE REVIEW

**Comment by pbek** [comment]
Doesn't it work with const?

**Comment by Waqar144** [comment]
> Doesn't it work with const?

It does, but there is a hint of problem we had, so how about revert constness just for this?

**Comment by pbek** [comment]
You mean https://github.com/pbek/QOwnNotes/commit/00f16e3e998e1102c8103e51fd4e5456280f4af5? No, that was an actual warning I got under Windows, because the DB connection was closed on a const DB. You didn't "see" that because you only work on Linux. :grin: 

I don't think we need this PR unless there is an actual problem.

**Comment by pbek** [comment]
I'll close this and keep it until there is an actual issue.

**Comment by Waqar144** [comment]
> You mean [00f16e3](https://github.com/pbek/QOwnNotes/commit/00f16e3e998e1102c8103e51fd4e5456280f4af5)? No, that was an actual warning I got under Windows, because the DB connection was closed on a const DB. You didn't "see" that because you only work on Linux. grin
> 
> I don't think we need this PR unless there is an actual problem.

Alright.

**Pull request closed without merging**
