### PR TITLE
Use static QregularExpressions to improve performance

### PR DESCRIPTION
**Pull request by Waqar144**
Constructing `QRegularExpression` is very expensive.

The change doesn't fix all the usages(since there are too many). I have fixed the ones that are more commonly used.

### CODE REVIEW

**Comment by data-man** [comment]
Just migrate to [CTRE](https://github.com/hanickadot/compile-time-regular-expressions).

**Comment by Waqar144** [comment]
> Just migrate to [CTRE](https://github.com/hanickadot/compile-time-regular-expressions).

That's.. pointless? and probably not even possible for us to completely migrate to it even if we wanted to, which again, is completely pointless for us.

**Comment by pbek** [comment]
LGTM, thank you very much. 😁

**Comment by data-man** [comment]
Yes, CTRE is only for powerful skills :rofl:

**Comment by Waqar144** [comment]
Not sure if I understand you, If we only support one extension in this
case, then we don't even need to check for the default extension, right?

**Comment by pbek** [comment]
## 21.10.9
- there now will be a warning that a restart of the application is needed when
  changing the default note file extension (for [#2250](https://github.com/pbek/QOwnNotes/pull/2250))

**Comment by Waqar144** [comment]
https://github.com/pbek/QOwnNotes/pull/2267 created for the above.

**Comment by pbek** [comment]
I liked your static variable. I didn't want to bother implementing that all with new variable for a use-case that happens once in a thousand years (someone changing the default note file extension) 🤣 

> #2267 created for the above.

...just needs some fixes 😉

**Pull request merged**
