### PR TITLE
Downgrade to C++14

### PR DESCRIPTION
**Pull request by Waqar144**
gcc 4.8.x doesn't support C++17

### CODE REVIEW

**Comment by pbek** [comment]
There still seems to be a problem on Ubuntu 18.04 for the AppImage build: https://github.com/pbek/QOwnNotes/runs/5195670986?check_suite_focus=true

**Comment by Waqar144** [comment]
> There still seems to be a problem on Ubuntu 18.04 for the AppImage build: https://github.com/pbek/QOwnNotes/runs/5195670986?check_suite_focus=true

pushed a fix, but that only affects the github CI or anyone using DEV_MODE

**Comment by Waqar144** [comment]
I have disabled `-pedantic` but that is the wrong fix. Better would be that you disable `DEV_MODE` for this specific appimage build instead. That flag is important if you want to be sure that we only have C++14 code, and not C++17 and thus prevent failures in places like OBS etc.

**Comment by pbek** [comment]
> Better would be that you disable DEV_MODE for this specific appimage build instead. 

For OBS you could attempt to do that in https://github.com/pbek/QOwnNotes/blob/develop/obs/appimage.yml
I wonder why the GitHub AppImage build went through...

**Comment by Waqar144** [comment]
> 

The build went through because I disabled the flag. OBS builds should succeed now anyways. I meant that we should disable `config+=DEV_MODE` for github appimage build to catch build errors early here rather than find out in OBS.

**Comment by pbek** [comment]
Still a lot of broken builds on OBS: https://build.opensuse.org/package/show/home:pbek:QOwnNotes/desktop

**Comment by Waqar144** [comment]
> Still a lot of broken builds on OBS: https://build.opensuse.org/package/show/home:pbek:QOwnNotes/desktop

Which distro does the AppImage use?

**Comment by pbek** [comment]
Hard to tell from https://build.opensuse.org/package/live_build_log/home:pbek:QOwnNotes/desktop/AppImage/x86_64, the user has no control about that.

**Comment by Waqar144** [comment]
can the compiler be updated there?

**Comment by pbek** [comment]
Not that I know of. You only have control over the appimage.yml.

**Comment by Waqar144** [comment]
we can use `-std=c++1y`, but that flags implies experimental 14 support, which means somethings might not work at some point.

**Pull request merged**
