### PR TITLE
Update to new inline highlighter

### PR DESCRIPTION
**Pull request by Waqar144**

### CODE REVIEW

**Comment by pbek** [comment]
My dev QON now crashes with a `Fatal: ASSERT: "uint(i) < uint(size())" in file /usr/include/x86_64-linux-gnu/qt5/QtCore/qstring.h, line 934 (/usr/include/x86_64-linux-gnu/qt5/QtCore/qstring.h:934, (null))` upon startup. :laughing:

**Comment by pbek** [comment]
code: `const bool isHeading = text.at(0) == QChar('#');`

```
1  __GI_raise                                           raise.c                          51  0x7ffff3958e97 
2  __GI_abort                                           abort.c                          79  0x7ffff395a801 
3  QMessageLogger::fatal(const char *, ...) const                                            0x7ffff48efcbb 
4  qt_assert(const char *, const char *, int)                                                0x7ffff48ef4b1 
5  QString::at                                          qstring.h                        934 0x5555555ebe8d 
6  QOwnNotesMarkdownHighlighter::highlightMarkdown      qownnotesmarkdownhighlighter.cpp 113 0x555555799844 
7  QOwnNotesMarkdownHighlighter::highlightBlock         qownnotesmarkdownhighlighter.cpp 95  0x5555557996af 
8  ??                                                                                        0x7ffff68e2660 
9  ??                                                                                        0x7ffff68e2820 
10 QSyntaxHighlighter::rehighlight()                                                         0x7ffff68e2be7 
11 QOwnNotesMarkdownTextEdit::updateSettings            qownnotesmarkdowntextedit.cpp    470 0x5555557aa0ed 
12 QOwnNotesMarkdownTextEdit::QOwnNotesMarkdownTextEdit qownnotesmarkdowntextedit.cpp    26  0x5555557a770c 
13 Ui_LogWidget::setupUi                                ui_logwidget.h                   62  0x5555557fdcf6 
14 LogWidget::LogWidget                                 logwidget.cpp                    26  0x5555557fb50a 
15 LogWidget::createInstance                            logwidget.cpp                    303 0x5555557fcfbc 
16 LogWidget::instance                                  logwidget.cpp                    293 0x5555557fcf43 
17 MainWindow::MainWindow                               mainwindow.cpp                   120 0x5555555efee5 
18 main                                                 main.cpp                         532 0x5555555d91be 
```

the note text was

```
Checkbox list test
==================

- [ ] un-checked
- [] un-checked no space
- [x] checked
```

**Comment by Waqar144** [comment]
Fixed

**Comment by pbek** [comment]
yes, fixed

**Pull request merged**
