### PR TITLE
Add support for tilde code fence highlighting

### PR DESCRIPTION
**Pull request by Waqar144**
#1580

### CODE REVIEW

**Comment by pbek** [comment]
Building works.
The highlightings doesn't seem to work if you open a note with tilde code fences. It works as soon you are editing the code block.

```markdown
Code block test
===============

~~~
sdfs <strong>strong</strong>
~~~

~~~css
a {color: green;}
~~~
```

**Comment by Waqar144** [comment]
> Building works.
> The highlightings doesn't seem to work if you open a note with tilde code fences. It works as soon you are editing the code block.
> 
> ```gfm
> Code block test
> ===============
> 
> ~~~
> sdfs <strong>strong</strong>
> ~~~
> 
> ~~~css
> a {color: green;}
> ~~~
> ```

That's weird. Its working for me just like before,

**Comment by pbek** [comment]
And highlighting also runs wild when you use 3xtick inside a tilde fence or 3xtide inside a tick fence.

**Comment by Waqar144** [comment]
> And highlighting also runs wild when you use 3xtick inside a tilde fence or 3xtide inside a tick fence.

Yeah, that would happen. There's not much protection for that yet. And it'd be _very_ hard to handle that correctly I think.

**Comment by pbek** [comment]
> That's weird. Its working for me just like before,

image

> Yeah, that would happen. There's not much protection for that yet. And it'd be very hard to handle that correctly I think.

Hehe, for me the only use-case for tilde fences is when I want to fence tick fences. :grin:

**Comment by pbek** [comment]
Strangely this note is highlighted immediately:

    Code block test stacked
    ===============
    
    ~~~
    sdfs <strong>strong</strong>
    ~~~
    
    ~~~
    ```
    inner
    ```
    
    sdfs <strong>strong</strong>
    ~~~
    
    
    ~~~css
    a {color: green;}
    ~~~
    
    ```css
    a {color: green;}
    ```
    ```
    a {color: green;}
    ~~~
    adas
    ~~~
    ```

image

**Comment by Waqar144** [comment]
# Meanwhile for me:

image

**Comment by Waqar144** [comment]
Yes, now i can reproduce it too

**Comment by Waqar144** [comment]
Fixed

**Comment by pbek** [comment]
Initial highlighting works. Great job! :grin: 

But `Code block test stacked` still highlights the same.

**Pull request merged**
