### PR TITLE
improve it translation

### PR DESCRIPTION
**Pull request by Manu-sh**

### CODE REVIEW

**Comment by pbek** [comment]
Thank you for your suggestions, but I'm sorry, I cannot merge this pull request. It would destroy all meta information from Crowdin. If you want to improve the translation please do so on <https://crowdin.com/translate/qownnotes/1/en-it>.

**Comment by pbek** [comment]
And if you do please comment on why you think it should be changed (and create the comment as an issue if the translation is wrong).

PS: You can invite yourself to Crowdin with: <https://crowdin.com/project/qownnotes/invite>

**Comment by Manu-sh** [comment]
Ah okay, maybe tomorrow

**Comment by Manu-sh** [comment]
Ok, i have provided to improve IT translation on crowdin

**Comment by pbek** [comment]
Thanks you!

**Pull request closed without merging**
