### PR TITLE
Dont refetech the note in Note::exists, just check the id

### PR DESCRIPTION
**Pull request by Waqar144**

### CODE REVIEW

**Comment by Waqar144** [comment]
This is unnecessary. I realized we can just use `isFetched()` correctly in the places where two fetches are happening.

**Comment by pbek** [comment]
Hm, there were cases where a note object or note id was stored somewhere, but the internal note database was already reloaded. Theses cases wouldn't be handled correctly any more, since the note id would be > 0, but the note wouldn't actually exist any more... Hm, but loading the note wouldn't actually help neither...

**Comment by pbek** [comment]
Oh, you closed it. Sorry, I'm a bit slow. Had a very painful tooth extraction... Still very painful.

**Comment by Waqar144** [comment]
> Oh, you closed it. Sorry, I'm a bit slow. Had a very painful tooth extraction... Still very painful.

Haha, its fine. I created another one with `isFetched()`

**Pull request closed without merging**
